const gameDescriptions = {
    // --- NUMBERS & A ---
    "999 & Virtue's Last Reward": "Trapped in a game of life and death, nine people must escape a sinking ship. A visual novel masterpiece of suspense and puzzles.",
    "ACE COMBAT™ 7: SKIES UNKNOWN": "Become an ace pilot and soar through photorealistic skies with full 360-degree movement in this intense aerial combat simulator.",
    "Aerial_Knights Never Yield": "A 3D side-scroller that plays like a classic endless runner. Survive a futuristic Detroit in this stylish narrative adventure.",
    "AI War 2": "The most devious and acclaimed artificial intelligence in strategy gaming returns. A grand strategy/RTS hybrid against an overwhelming enemy.",
    "AI: The Somnium Files": "In a near-future Tokyo, Detective Kaname Date chases a serial killer. Dive into dreamscapes to uncover clues in this sci-fi mystery.",
    "AI: THE SOMNIUM FILES - nirvanA Initiative": "Two protagonists, Past and Present, link up to solve the mystery of the Half Body serial killings in this mind-bending sequel.",
    "Airship: Kingdoms Adrift": "Build and command your own airship. Explore the skies, trade, and fight in a steampunk world of floating islands.",
    "Alan Wake": "When the wife of best-selling writer Alan Wake disappears on their vacation, his search turns up pages from a thriller he doesn’t remember writing.",
    "Alan Wake's American Nightmare": "Alan Wake fights the herald of darkness, Mr. Scratch, in a new standalone story experience featuring a pulp-action game mode.",
    "Alice: Madness Returns": "Return to a Wonderland gone wrong. Alice must battle the corruption in her mind and the world using legendary weapons.",
    "Ancestors Legacy": "A squad-based real-time strategy game with a strong focus on tactics. Command Vikings, Anglo-Saxons, Germans, or Slavs.",
    "Andro Dunos 2": "The sequel to the classic 1992 scrolling shooter. Defend the earth once again in this retro-style shmup.",
    "Arcade Paradise": "Manage the family laundromat while turning it into the ultimate arcade. Wash clothes, unclog toilets, and build your gaming empire.",
    "ArcaniA": "War covers the southern islands. A nameless hero rises to seek revenge against King Rhobar IV in this fantasy RPG.",
    "ArcaniA: Fall of Setarrif": "A standalone expansion for ArcaniA. Face a new demonic threat and save the coastal city of Setarrif.",
    "ARMORED CORE™ VI FIRES OF RUBICON™": "Assemble and pilot your own mech with 3D maneuverability. Engage in fast-paced, omni-directional battles in this FromSoftware action title.",
    "Arx Fatalis": "A first-person RPG set in a world where the sun has failed, forcing humanity into underground caverns.",
    "The Ascent": "A solo and co-op Action-shooter RPG set on Veles, a packed cyberpunk world. Stop the gangs and hostile corps from taking over.",
    "Assassin's Creed Director's Cut": "The game that started it all. As Altaïr, master the skills of the Assassins and alter the course of history in the Holy Land.",
    "Astalon: Tears of the Earth": "Three explorers wander through a post-apocalyptic desert to find a way to save their village in this 8-bit style action-platformer.",

    // --- B ---
    "Balatro": "The poker roguelike. Play illegal poker hands, discover game-changing jokers, and trigger adrenaline-pumping combos.",
    "Baldur's Gate 3": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power.",
    "Bang-On Balls: Chronicles": "A quirky, 3D platformer combat game where you become a reckless hero. Do missions, collect items, and smash everything.",
    "Bastion": "An action RPG that redefines storytelling in games, with a reactive narrator who marks your every move.",
    "Batman: Arkham Asylum GOTY Edition": "Descend into the madness of Arkham Asylum and battle Gotham's most notorious villains in this award-winning action game.",
    "Batman: Arkham City GOTY": "Explore Arkham City, a sprawling mega-prison in the heart of Gotham, home to its most violent thugs and super villains.",
    "Batman™: Arkham Knight": "The explosive finale to the Arkham series. Batman faces the ultimate threat against the city he is sworn to protect.",
    "Batman™: Arkham Origins": "Features an expanded Gotham City and introduces an original prequel storyline set several years before the events of Arkham Asylum.",
    "Bayonetta": "From PlatinumGames' legendary director Hideki Kamiya comes the climax of action. Stylish, fast-paced, and intense.",
    "Beholder: Conductor": "You are a conductor on the legendary Grim Train. Spy on passengers, report incidents, and decide the fate of the people aboard.",
    "Berserk Boy": "Go Berserk! A high-speed 2D action platformer. Change forms and use the power of Lightning, Fire, Earth, Air, and Ice.",
    "Beyond: Two Souls": "Live the life of Jodie Holmes, a woman connected to a supernatural entity, in this psychological action thriller.",
    "The Binding of Isaac: Rebirth": "A randomly generated action RPG shooter with heavy Rogue-like elements. Escape the basement and your mom.",
    "BioGun": "Inject yourself into a microscopic world. Fight viruses and save the creator's dog in this metroidvania shooter.",
    "BIOMUTANT": "An open-world, post-apocalyptic Kung-Fu fable RPG, with a unique martial arts styled combat system.",
    "BioShock": "A shooter unlike any you've ever played. Explore the underwater city of Rapture and use genetic modifications to survive.",
    "BioShock 2": "Set approximately 10 years after the original. Step into the boots of the most iconic denizen of Rapture, the Big Daddy.",
    "BioShock 2 Remastered": "High resolution textures, models and interface for the classic sequel. Return to Rapture in full HD.",
    "BioShock Infinite": "Indebted to the wrong people, Booker DeWitt must travel to the flying city of Columbia to rescue a mysterious girl named Elizabeth.",
    "BioShock Remastered": "The weapons, plasmids, and waters of Rapture have never looked better. The definitive version of the classic shooter.",
    "The Black Grimoire: Cursebreaker": "A narrative-driven classic RPG experience inspired by old-school runescape and ultima online.",
    "Black Mesa": "The fan-made reimagining of Valve's Half-Life. You are Gordon Freeman, a theoretical physicist at the Black Mesa Research Facility.",
    "Black Myth: Wukong": "Set out as the Destined One in this action RPG rooted in Chinese mythology. Uncover the truth beneath a glorious legend.",
    "Blasphemous": "A brutal action-platformer with skilled hack-n-slash combat set in the nightmare world of Cvstodia.",
    "Bloodstained: Curse of the Moon": "An 8-bit style action game promised as a stretch goal for the Bloodstained Kickstarter. A retro tribute.",
    "Bloodstained: Curse of the Moon 2": "Zangetsu returns in this 8-bit style sequel. Features a new story and four playable characters.",
    "Bloodstained: Ritual of the Night": "An exploration-focused side-scroller action RPG packing all of the best features you've come to know and love from the Metroidvania genre.",
    "Blue Prince": "Inherit a mysterious mansion. Explore its shifting rooms and uncover the secrets of the Blue Prince.",
    "Bomber Crew": "A strategic simulation game where picking the right crew and keeping your bomber in the air is the difference between completing your mission or losing it all.",
    "Borderlands 2": "A new era of shoot and loot is about to begin. Play as one of four new vault hunters facing off against Handsome Jack.",
    "Borderlands 3": "The original shooter-looter returns, packing bazillions of guns and an all-new mayhem-fueled adventure.",
    "Bramble: The Mountain King": "A grim adventure set in a world inspired by dark Nordic fables. Explore a beautiful but dangerous and twisted land.",
    "Bridge Constructor Portal": "Enter the Aperture Science Enrichment Center and experience Bridge Constructor with a Portal twist.",
    "Bright Memory: Infinite": "A high-octane FPS and action combo game. Mix gunplay with sword skills in a futuristic setting.",
    "Broken Roads": "A narrative-driven RPG set in a post-apocalyptic Australian Outback. Your choices shape your moral compass.",
    "Brothers: A Tale of Two Sons Remake": "Guide two brothers on an epic fairy tale journey in this remake of the acclaimed adventure game.",
    "Buckshot Roulette": "Play Russian Roulette with a 12-gauge shotgun. Intense, high-stakes, and darker than you can imagine.",
    "Bully: Scholarship Edition": "As a troublesome schoolboy, you'll stand up to bullies, get picked on by teachers, play pranks, and win or lose the girl.",
    "Bulwark: Falconeer Chronicles": "An open world builder with freedom and expression at its core. Build sprawling towns, spires, and fortifications.",
    "BUTCHER": "A fast-paced 2D shooter and a blood-soaked love letter to the cult classics of the genre.",

    // --- C ---
    "Call of Duty: Black Ops II": "Pushing the boundaries of what fans have come to expect from the record-setting entertainment franchise.",
    "Call of Duty: Black Ops III": "Deploys players into a dark, twisted future where a new breed of Black Ops soldier emerges.",
    "Call of Juarez: Bound in Blood": "The Old West, 1864. In order to save their family, the McCall brothers will kill anyone who stands between them and the legendary Gold of Juarez.",
    "Capcom Beat 'Em Up Bundle": "Seven classic side-scrolling arcade beat 'em ups, including Final Fight and Captain Commando.",
    "CARRION": "A reverse horror game in which you assume the role of an amorphous creature of unknown origin.",
    "Castlevania Anniversary Collection": "Konami's origins of the vampire franchise. Includes essential titles like Castlevania I, II, III, and Super Castlevania IV.",
    "Castlevania Advance Collection": "Count Dracula is back from the dead... Join the fight against Evil in the Castlevania Advance Collection.",
    "Castle Crashers": "Hack, slash, and smash your way to victory in this award-winning 2D arcade adventure.",
    "Celeste": "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer.",
    "Chained Together": "Begin your journey in the depths of hell, chained to your companions. Climb as high as possible to escape.",
    "Chicory: A Colorful Tale": "A top-down adventure game in a coloring book world where you can draw on anything.",
    "CHRONO TRIGGER": "The timeless RPG classic returns loaded with upgrades. Journey to the forgotten past, the far future, and the end of time.",
    "Citizen Sleeper": "Roleplaying in the ruins of interplanetary capitalism. Live the life of an escaped worker on a lawless station.",
    "Clive 'N' Wrench": "A 3D platformer starring Clive, a rabbit, and Wrench, the monkey on his back. Travel through time and space.",
    "Cobalt Core": "A sci-fi roguelike deckbuilder with a unique single-axis combat system. Dodge missiles and jump cannons.",
    "CODE VEIN": "Team up with an AI partner or a friend in co-op multiplayer and venture out into a world of destruction in this story driven dungeon experience.",
    "Colt Canyon": "A 2D pixel art shooter where you control a cowboy, or one of the many other unlockable characters, whose mission is to save his kidnapped partner.",
    "Company of Heroes 3": "The legendary strategy franchise is back. Mediterranean theater brings a new unparalleled scale of war.",
    "Content Warning": "Film your friends doing scary things to become SpookTube famous in this co-op horror game.",
    "Control Ultimate Edition": "A supernatural 3rd person action-adventure that will challenge you to master the combination of supernatural abilities, modifiable loadouts and reactive environments.",
    "Cook, Serve, Delicious!": "A hardcore restaurant sim, one of the few in its genre that gives the players total control over their menu and restaurant.",
    "Cook, Serve, Delicious! 2!!": "The massive sequel to the surprise hit. Rebuild your restaurant in the Teragon Supertower.",
    "Crash Bandicoot™ N. Sane Trilogy": "Your favorite marsupial, Crash Bandicoot, is back. Enhanced, entranced & ready-to-dance.",
    "CRISIS CORE –FINAL FANTASY VII– REUNION": "The prequel to FINAL FANTASY VII. The story of Zack Fair, a young warrior admired by the boy destined to save the world.",
    "Crypt of the NecroDancer": "An award winning hardcore roguelike rhythm game. Move to the beat and battle dancing skeletons.",
    "Cuphead": "A classic run and gun action game heavily focused on boss battles, inspired by cartoons of the 1930s.",

    // --- D ---
    "Danganronpa: Trigger Happy Havoc": "Hope's Peak Academy is home to Japan's best and brightest high school students—the beacons of hope for the future. But that hope suddenly dies when Makoto Naegi and his classmates find themselves imprisoned in the school.",
    "Danganronpa 2: Goodbye Despair": "Jabberwock Island—once a popular tourist destination, this now uninhabited island remains oddly pristine. You and your classmates at the elite Hope's Peak Academy have been brought to this island by your super-cute teacher for a 'lovey-dovey, heart-throbbing school trip.'",
    "Danganronpa V3: Killing Harmony": "A new cast of 16 characters find themselves kidnapped and imprisoned in a school. Inside, some will kill, some will die, and some will be punished.",
    "The Dark Eye: Chains of Satinav": "Face your destiny! In Andergast, the inhabitants differ from the rest of Aventuria. A young bird catcher finds himself in a grand adventure.",
    "Dark Messiah of Might & Magic": "Discover a new breed of Action-RPG game powered by an enhanced version of the Source™ Engine. Brutal first-person combat.",
    "DARK SOULS™ II: Scholar of the First Sin": "The definitive edition of Dark Souls II. Includes all 3 DLC packs and enhanced graphics.",
    "DARK SOULS™ III": "As fires fade and the world falls into ruin, journey into a universe filled with more colossal enemies and environments.",
    "DARK SOULS™: REMASTERED": "Then, there was fire. Re-experience the critically acclaimed, genre-defining game that started it all.",
    "Darksiders": "Deceived by the forces of evil into prematurely bringing about the end of the world, War – the first Horseman of the Apocalypse – is accused of breaking the sacred law.",
    "Darksiders Genesis": "An action/adventure that tears its way through hordes of demons, angels, and everything in-between on its way to Hell and back.",
    "Darksiders II Deathinitive Edition": "Become Death, the most feared of the legendary Four Horsemen, able to destroy entire worlds and battle forces beyond Heaven and Hell.",
    "Darksiders III": "Return to an apocalyptic Earth in this hack-n-slash action adventure where players assume the role of FURY in her quest to hunt down and dispose of the Seven Deadly Sins.",
    "Darksiders Warmastered Edition": "War's redemption. The first game in the series remastered with 4k support and doubled texture resolutions.",
    "Days Gone": "Ride and fight into a deadly, post-pandemic America. Play as Deacon St. John, a drifter and bounty hunter who rides the broken road.",
    "Dead by Daylight": "A multiplayer (4vs1) horror game where one player takes on the role of the savage Killer, and the other four players play as Survivors.",
    "Dead Cells": "A rogue-lite, metroidvania action-platformer. You'll explore a sprawling, ever-changing castle... assuming you're able to fight your way past its keepers.",
    "Dead Rising 2": "Chuck Greene competes in the terror reality show 'Terror Is Reality' to afford Zombrex for his infected daughter.",
    "Dead Space (2023 Remake)": "Isaac Clarke is an everyman engineer on a mission to repair a vast mining ship, the USG Ishimura, only to discover something has gone horribly wrong.",
    "Dead Space 2": "Engineer Isaac Clarke returns for another blood-curdling adventure in the sequel to the critically acclaimed Dead Space.",
    "Deadly Premonition: The Director's Cut": "Playing as special agent Francis York Morgan, investigate the brutal murder of a young local beauty in the town of Greenvale.",
    "Deadly Premonition 2": "A Blessing in Disguise. This sequel takes place in present-day Boston but tells a prequel story set in Le Carré.",
    "Death's Gambit: Afterlife": "A challenging 2D action-platformer with deep RPG elements. Master the precise combat and face the horrors of Siradon.",
    "DEATH STRANDING DIRECTOR'S CUT": "From legendary game creator Hideo Kojima comes a genre-defying experience. Sam Bridges must brave a world utterly transformed by the Death Stranding.",
    "Defense Grid: The Awakening": "The ultimate tower defense game that appeals to players of all skill levels. Defend the cores from the alien horde.",
    "Deliver Us The Moon": "A Sci-Fi thriller set in an apocalyptic near future, where Earth's natural resources are depleted. A lone astronaut is sent to the moon.",
    "Desperados - Wanted Dead or Alive": "A strategy game that combines movie-based atmosphere with challenging tactical gameplay in the Wild West.",
    "Desperados 2: Cooper’s Revenge": "The sequel to the successful wild west title. Switch between isometric view and third-person view.",
    "Desperados III": "A story-driven, hardcore tactical stealth game, set in a ruthless Wild West scenario. A prequel to the beloved classic.",
    "Destroy All Humans!": "The cult classic returns! Terrorize the people of 1950s Earth in the role of the evil alien Crypto-137.",
    "Detroit: Become Human": "Detroit, 2038. Technology has evolved to a point where androids are everywhere. Decisions you make shape the story.",
    "Deus Ex: Human Revolution - Director's Cut": "You play Adam Jensen, an ex-SWAT specialist who's been handpicked to oversee the defensive needs of one of America's most experimental biotech firms.",
    "Deus Ex: Mankind Divided™": "Now an experienced covert operative, Adam Jensen is forced to operate in a world that has grown to despise his kind.",
    "Devil May Cry HD Collection": "The popular stylish action games Devil May Cry, Devil May Cry 2, and Devil May Cry 3 Special Edition in one collection.",
    "Devil May Cry 4 Special Edition": "Control Nero and Dante in this special edition featuring new characters like Vergil, Lady, and Trish.",
    "Devil May Cry 5": "The ultimate Devil Hunter is back in style, in the game action fans have been waiting for.",
    "Digimon Story Cyber Sleuth: Complete Edition": "Become a cyber detective or a powerful hacker to solve diabolical digi-mysteries.",
    "Digimon World: Next Order": "The Digital World is in despair. Machinedramons are running rampant and causing utter chaos.",
    "Disco Elysium - The Final Cut": "A groundbreaking role playing game. You’re a detective with a unique skill system at your disposal.",
    "Dishonored": "An immersive first-person action game that casts you as a supernatural assassin driven by revenge.",
    "Dishonored 2": "Reprise your role as a supernatural assassin in Dishonored 2. Play your way in a world where mysticism and industry collide.",
    "Dishonored®: Death of the Outsider™": "Take on the role of Billie Lurk as she reunites with her old mentor, Daud, to undertake the greatest assassination ever conceived.",
    "Dispatch": "A narrative thriller. Manage emergency calls and dispatch resources while unraveling a dark mystery.",
    "Divinity: Original Sin 2 - Definitive Edition": "The critically acclaimed RPG that raised the bar, from the creators of Baldur's Gate 3.",
    "DmC: Devil May Cry": "A retelling of Dante's origin story set against a contemporary backdrop. Stylish action and fluid combat.",
    "Don't Starve": "An uncompromising wilderness survival game full of science and magic. Enter a strange and unexplored world.",
    "Don't Starve Together": "The standalone multiplayer expansion of the uncompromising wilderness survival game, Don't Starve.",
    "DOOM (1993)": "The game that popularized the first-person shooter. Rip and tear through demons from Hell.",
    "DOOM II": "The sequel to the groundbreaking DOOM (1993), giving players the brutal Super Shotgun to bear against deadlier demons.",
    "DOOM 3": "A terrifying battle with the forces of Hell. A critically acclaimed horror/action masterpiece.",
    "DOOM 3: BFG Edition": "The ultimate collection of games that defined the first person shooter. Includes DOOM, DOOM II, DOOM 3.",
    "DOOM 64": "Originally released on the Nintendo 64 in 1997, Doom 64 is an action first-person shooter now on PC.",
    "DOOM Eternal": "Hell’s armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions.",
    "Double Kick Heroes": "A rhythm metal shooter where you survive on the highway to hell by killing monsters with your gundillac.",
    "DRAGON BALL XENOVERSE 2": "Relive the Dragon Ball story by time traveling and protecting historic moments in the Dragon Ball universe.",
    "DRAGON BALL Z: KAKAROT": "Relive the story of Goku and other Z Fighters in this Action RPG. Fight, fish, eat, and train.",
    "DRAGON BALL: Sparking! ZERO": "The legendary gameplay of the Budokai Tenkaichi series returns. Unleash the fighting spirit within you.",
    "Dragon Is Dead": "A side-scrolling action roguelite. Challenge the Dragon Guernian and the dark legions he commands.",
    "Dragon's Dogma: Dark Arisen": "A huge open world action RPG. Set out on an epic adventure with your Pawn companions.",
    "Dungeon Tycoon": "Build your own dungeon, attract heroes, and profit from their demise in this management strategy game.",
    "Dying Light": "A first-person action survival game set in a post-apocalyptic open world overrun by flesh-hungry zombies.",
    "Dying Light 2 Stay Human": "The virus won and civilization has fallen back to the Dark Ages. The City is on the brink of collapse. Use your agility and combat skills to survive.",

    // --- E ---
    "ELDEN RING": "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord.",
    "The Elder Scrolls III: Morrowind GOTY": "An epic, open-ended single-player RPG where you can create and play any kind of character you can imagine.",
    "The Elder Scrolls IV: Oblivion GOTY": "Step inside the most richly detailed and vibrant game-world ever created in this chapter of the Elder Scrolls saga.",
    "The Elder Scrolls V: Skyrim Special Edition": "Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail.",
    "The Elder Scrolls V: Skyrim VR": "A true, full-length open-world game for VR from Bethesda Game Studios.",
    "ENDER LILIES: Quietus of the Knights": "Unravel the mysteries of a destroyed kingdom in this dark fantasy 2D action RPG.",
    "ENDER MAGNOLIA: Bloom in the Mist": "The sequel to ENDER LILIES. Explore a land of fumes and machines in this 2D action RPG.",
    "Enter the Gungeon": "A bullet hell dungeon crawler following a band of misfits seeking to shoot, loot, dodge roll and table-flip their way to personal absolution.",
    "Epic Chef": "A story-driven adventure game flavored with life-sim, cooking, and crafting elements.",
    "Euro Truck Simulator 2": "Travel across Europe as king of the road, a trucker who delivers important cargo across impressive distances.",
    "Everhood": "An ineffable RPG where the battles are rhythm-based. Expect the unexpected.",
    "The Evil Within": "Developed by Shinji Mikami, creator of the seminal Resident Evil series. Pure survival horror.",
    "The Evil Within 2": "Sebastian Castellanos has lost everything. But when given a chance to save his daughter, he must descend once more into the nightmarish world of STEM.",
    "Evil Genius 2: World Domination": "A satirical spy-fi lair builder, where YOU are the criminal mastermind! Construct your evil lair.",

    // --- F ---
    "F.E.A.R.": "Be the hero in your own spine-tingling cinematic action thriller of mystery and horror.",
    "F.E.A.R. 2: Project Origin": "A supernatural entity is free and threatens to destroy a major American city. You are the only one who can stop it.",
    "F.E.A.R. 3": "Alma is expecting. And a new level of terror grows as you and your cannibal brother battle through a hellish nightmare.",
    "Fahrenheit: Indigo Prophecy Remastered": "A paranormal thriller where New York City is stunned by a series of mysterious murders.",
    "Fallout 3 - Game of the Year Edition": "Prepare for the Future. Experience the most acclaimed game of 2008 like never before.",
    "Fallout 4": "As the sole survivor of Vault 111, you enter a world destroyed by nuclear war. Every second is a fight for survival.",
    "Fallout: New Vegas": "Welcome to Vegas. New Vegas. It’s the kind of town where you dig your own grave prior to getting shot in the head.",
    "Far Cry": "A tropical paradise seethes with hidden evil. Jack Carver finds himself hunted by mercenary groups.",
    "Far Cry 2": "You are a gun for hire, trapped in a war-torn African state, stricken with malaria and forced to make deals with corrupt warlords.",
    "FINAL FANTASY": "The game that started it all. The Warriors of Light set out on a journey to restore the crystals to their former luster.",
    "FINAL FANTASY II": "Our epic tale begins with four young souls orphaned during the struggle between the Palamecian Empire and the rebel army.",
    "FINAL FANTASY III": "The power of light is nearly eclipsed by the power of darkness, and only the crystals' chosen four adventurers can save the world.",
    "FINAL FANTASY IV": "The Dark Knight Cecil, stripped of his command, sets out on a journey of redemption.",
    "FINAL FANTASY V": "The King of Tycoon has sensed a disturbance in the wind. When the crystals shatter, the world's balance is lost.",
    "FINAL FANTASY VI": "The War of the Magi left nothing but ashes and misery. A thousand years later, magic has vanished from the world.",
    "FINAL FANTASY VII (Original)": "The RPG classic. Cloud Strife, a former SOLDIER operative, joins the resistance group AVALANCHE.",
    "FINAL FANTASY VII REMAKE INTERGRADE": "A spectacular reimagining of one of the most visionary games ever. Cloud Strife fights to save the planet from Shinra.",
    "FINAL FANTASY VII REBIRTH": "The journey unknown continues. Cloud and his comrades escape Midgar and travel across the planet.",
    "FINAL FANTASY VIII - REMASTERED": "The Republic of Galbadia is under the influence of the sorceress Edea. Squall Leonhart must stop her.",
    "FINAL FANTASY IX": "Zidane and the Tantalus Theater Troupe have kidnapped Princess Garnet. A grand adventure begins.",
    "FINAL FANTASY X/X-2 HD Remaster": "Relive two of the greatest RPGs of their generation, completely remastered.",
    "FINAL FANTASY XII THE ZODIAC AGE": "Return to the World of Ivalice. A remaster of the classic high-fantasy RPG.",
    "FINAL FANTASY XIII": "A deepening crisis threatens the floating world of Cocoon. Lightning and a band of unlikely heroes must save it.",
    "FINAL FANTASY XIII-2": "Set three years after FINAL FANTASY XIII. Lightning has gone missing, and her sister Serah sets out to find her.",
    "LIGHTNING RETURNS: FINAL FANTASY XIII": "The world is ending in 13 days. Lightning returns as the Savior to save as many souls as possible.",
    "FINAL FANTASY XV WINDOWS EDITION": "Join Prince Noctis and his closest friends as they fight against the empire to take back their fallen kingdom.",
    "FINAL FANTASY XVI": "An epic dark fantasy where the fates of the land are decided by the mighty Eikons and the Dominants who wield them.",
    "FINAL FANTASY TYPE-0 HD": "Step into the fray as Class Zero, a group of students from an elite military academy.",
    "Firewatch": "A single-player first-person mystery set in the Wyoming wilderness.",
    "The First Berserker: Khazan": "A hardcore action RPG based on the DNF universe. Khazan seeks revenge against those who ruined him.",
    "Fractured Minds": "A short immersive artistic game that explores anxiety and mental health issues.",
    "The friends of Ringo Ishikawa": "A high school gang leader and his friends try to live through their best days. An existential open world beat 'em up.",
    "Furi": "You were captured. Look what they’ve done to you. The jailer is the key, kill him and you’ll be free.",

    // --- G ---
    "Gang Beasts": "A silly multiplayer party game with surly gelatinous characters, brutal slapstick fight sequences, and absurd hazardous environments.",
    "Garden in!": "A cozy sandbox game about growing plants. Relax, take care of your seedlings, and watch your dream garden grow.",
    "Gatekeeper": "A fast-paced rogue-lite. Go on a quest to find the stolen Heart of the Universe and shoot your way through hordes of machine enemies.",
    "Gato Roboto": "Pounce inside of your cozy armored mech and set off on a dangerous trek through an alien underworld full of irritable creatures.",
    "GeoGuessr": "Embark on a journey that takes you all over the world. From the most desolate roads in Australia to the busy streets of New York City.",
    "Ghost of Tsushima DIRECTOR'S CUT": "Forge a new path and wage an unconventional war for the freedom of Tsushima in this open-world action adventure.",
    "Ghost Trick: Phantom Detective": "Solve your own murder in this quirky, puzzle-packed mystery classic from the creator of Ace Attorney.",
    "Ghostrunner": "A hardcore FPP slasher packed with lightning-fast action, set in a grim, cyberpunk megastructure.",
    "Ghostrunner 2": "Blood will run in the highly anticipated hardcore FPP slasher set one year after the events of Ghostrunner.",
    "God of War": "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters.",
    "God of War Ragnarök": "Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle.",
    "Golf With Your Friends": "Why have friends if not to play Golf... With Your Friends! Nothing is out of bounds as you take on courses with fast-paced, exciting, simultaneous mini golf.",
    "Gori: Cuddly Carnage": "Play as a badass murder-kitty on a death-dealing hoverboard in this fast-paced skate-and-slash game.",
    "Gothic 1 Classic": "War has been waged across the kingdom of Myrtana. You are thrown into the penal colony, a prison of magic and chaos.",
    "Gothic II: Gold Classic": "You have torn down the magical barrier and released the prisoners of the Mine Valley. Now the former criminals are causing trouble.",
    "Gothic 3": "A nameless hero becomes a legend. Myrtana is in chains, overrun by orcs. The fate of the kingdom is in your hands.",
    "The Great Ace Attorney Chronicles": "Immerse yourself in a dramatic yet charming and witty world of evidence-gathering, deduction and courtroom battles.",
    "GRIME": "Destroy... Absorb... Grow... GRIME is a fast and unforgiving Action-Adventure RPG.",
    "Grotto": "A mystical, narrative-focused experience. You are the Soothsayer. The one capable of talking with the stars and unveiling their messages.",
    "Guacamelee! Gold Edition": "A Metroidvania-style action-platformer set in a magical world inspired by traditional Mexican culture and folklore.",
    "Guacamelee! Super Turbo Championship Edition": "The definitive version of the smash hit. More levels, more enemies, more chicken.",
    "Guacamelee! 2": "Luchador Juan Aguacate is out of retirement for a stunning new Metroidvania-style adventure.",
    "GUILTY GEAR -STRIVE-": "The cutting-edge 2D/3D hybrid graphics pioneered in the Guilty Gear series have been raised to the next level.",

    // --- H ---
    "Hades": "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler.",
    "Hades II": "Battle beyond the Underworld using dark sorcery to take on the Titan of Time in this bewitching sequel.",
    "Half-Life": "Named Game of the Year by over 50 publications, Valve's debut title blends action and adventure with award-winning technology.",
    "Half-Life: Source": "A digitally remastered version of the critically acclaimed and best selling PC game, enhanced via Source technology.",
    "Half-Life: Opposing Force": "Return to the Black Mesa Research Facility as one of the military specialists assigned to eliminate Gordon Freeman.",
    "Half-Life: Blue Shift": "Return to Black Mesa as Barney Calhoun, the security guard sidekick who helped Gordon out of so many sticky situations.",
    "Half-Life 2": "The suspense, challenge and visceral charge of the original, and adds startling new realism and responsiveness.",
    "Half-Life 2: Deathmatch": "Fast multiplayer action set in the Half-Life 2 universe! HL2's physics adds a new dimension to deathmatch play.",
    "Half-Life: Alyx": "Valve’s VR return to the Half-Life series. It’s the story of an impossible fight against a vicious alien race known as the Combine.",
    "Halo: The Master Chief Collection": "The Master Chief’s iconic journey includes six games, built for PC and collected in a single integrated experience.",
    "Hardspace: Shipbreaker": "Slice spaceships to carve out a living in this sci-fi salvage simulator.",
    "A Hat in Time": "A cute-as-heck 3D platformer featuring a little girl who stitches hats for wicked powers.",
    "Heavy Rain": "Hunt a murderer known only as the Origami Killer. Four characters, four perspectives, one story.",
    "HELLDIVERS™ 2": "The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy.",
    "Hi-Fi RUSH": "Feel the beat as wannabe rockstar Chai and his ragtag team fight against an evil megacorp in a world that syncs to the music.",
    "High On Life": "Partner with charismatic talking guns to take down an alien drug cartel that wants to turn humanity into poppers.",
    "Hitman: Codename 47": "Enter the world of a hitman, where you must use stealth and tactical problem solving to assassinate your targets.",
    "Hitman 2: Silent Assassin": "Enter the realm of a retired assassin, forced back into action by treason. You may be a hired killer but you still have a sense of loyalty and justice.",
    "Hitman: Contracts": "Encounter the dark, psychology of Agent 47 in the most disturbing hits of his career.",
    "Hitman: Blood Money": "Agent 47 is back and this time he's paid in cold, hard cash. How the money is spent is up to you.",
    "Hitman: Absolution": "The original Assassin undertakes his most personal contract to date.",
    "HITMAN World of Assassination": "Enter the world of the ultimate assassin. HITMAN World of Assassination brings together the best of HITMAN, HITMAN 2 and HITMAN 3.",
    "Hogwarts Legacy": "Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens to tear the wizarding world apart.",
    "Hollow Knight": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes.",
    "Hollow Knight: Silksong": "Play as Hornet, princess-protector of Hallownest, and adventure through a whole new kingdom ruled by silk and song.",
    "Horizon Zero Dawn™ Complete Edition": "Experience the legendary quest of Aloy to unravel the mysteries of a future Earth ruled by Machines.",
    "Horizon Forbidden West™ Complete Edition": "Brave the Forbidden West, a majestic but dangerous frontier that conceals mysterious new threats.",
    "Hotline Miami": "A high-octane action game overflowing with raw brutality, hard-boiled gunplay and skull crushing close combat.",
    "Hotline Miami 2: Wrong Number": "The brutal conclusion to the Hotline Miami saga. Follow the paths of several distinct factions.",
    "How 2 Escape": "An escape-simulation game where two players will need to cooperate on asymmetrical gameplay and devices.",
    "Human Fall Flat": "A hilarious, light-hearted physics platformer set in floating dreamscapes that can be played solo or with up to 8 players.",
    "Hyper Light Drifter": "Echoes of a dark and violent past resonate throughout a savage land, steeped in treasure and blood.",

    // --- I, J, K ---
    "ibb & obb": "A two player cooperative game set in a puzzle filled world where gravity goes both up and down.",
    "I Was a Teenage Exocolonist": "Grow up on an alien planet. Choose who you want to be and who you want to love in this narrative RPG.",
    "IMMORTALITY": "Marissa Marcel was a film star. She made three movies. But none of the movies was ever released. And Marissa Marcel disappeared.",
    "In Sound Mind": "An imaginative first-person psychological horror with frenetic puzzles and unique boss fights.",
    "Injustice: Gods Among Us Ultimate Edition": "What if our greatest heroes became our greatest threat? DC Comics icons clash in this fighting game.",
    "Injustice™ 2": "Power up and build the ultimate version of your favorite DC legends in Injustice 2.",
    "The Inner World": "Robert is a novice, a bit clueless, but with a heart of gold. He lives a peaceful life as a court musician in wind monastery.",
    "Inscryption": "An inky black card-based odyssey that blends the deckbuilding roguelike, escape-room style puzzles, and psychological horror.",
    "Instruments of Destruction": "A vehicle-building sandbox featuring advanced physics-based destruction.",
    "Intravenous 2": "Tactical stealth action. Save your father, uncover secrets, and decide whether to kill or spare your enemies.",
    "Islets": "Take to the sky and reunite a fragmented world in this surprisingly wholesome metroidvania.",
    "JANITOR BLEEDS": "A retro-inspired horror game set in an old arcade. Play the haunted arcade cabinet JANITOR to save your life.",
    "Journey": "Explore the ancient, mysterious world of Journey as you soar above ruins and glide across sands to discover its secrets.",
    "Judgment": "From the team that brought you the Yakuza series comes a gripping psychological thriller.",
    "Just Cause": "Your world...Your rules! In Just Cause, you are a Latin field operative and specialist in regime change.",
    "Just Cause 2": "On the island of Panau, rival gangs war in the streets while the ruthless dictator Baby Panay exercises a system of oppression.",
    "Just Cause 3": "Rico Rodriguez returns to unleash chaos in the most creative and explosive ways imaginable.",
    "Just Cause 4": "Rogue agent Rico Rodriguez journeys to Solis, a huge South American world home of conflict, oppression and extreme weather conditions.",
    "Kalimba": "Jump, slide and fly your way through a dark underworld in this award-winning puzzle platformer.",
    "Katana ZERO": "A stylish neo-noir, action-platformer featuring breakneck action and instant-death combat.",
    "Keep Talking and Nobody Explodes": "One player is trapped in a room with a ticking bomb they must defuse. The other players are the Experts who must give instructions.",
    "Kill The Crows": "A fast-paced top-down arena shooter set in a twisted wild west.",
    "killer7": "Dive into a dark world of underground assassins in a tale of revenge as Harman Smith.",
    "Killing Floor": "A Co-op Survival Horror FPS set in the devastated cities and countryside of England.",
    "Killing Floor 2": "Descend into continental Europe where the outbreak caused by Horzine Biotech's failed experiment has quickly spread.",
    "KINGDOM HEARTS -HD 1.5+2.5 ReMIX-": "A collection of 6 unforgettable KINGDOM HEARTS experiences. Sora's journey begins here.",
    "KINGDOM HEARTS HD 2.8 Final Chapter Prologue": "A compilation of 3 magical KINGDOM HEARTS experiences that lead up to KINGDOM HEARTS III.",
    "KINGDOM HEARTS III + Re Mind": "Sora is joined by Donald Duck and Goofy to stop the evil Heartless from invading and overtaking the universe.",
    "Kingdom Come: Deliverance": "A story-driven open-world RPG that immerses you in an epic adventure in the Holy Roman Empire.",
    "Kingdom Come: Deliverance II": "A thrilling Action RPG, set amidst the chaos of a civil war in 15th Century Bohemia.",

    // --- L ---
    "The Last of Us™ Part I": "Experience the emotional storytelling and unforgettable characters in The Last of Us, winner of over 200 Game of the Year awards.",
    "Left 4 Dead": "Valve's survival co-op FPS that pits four survivors against hordes of zombies.",
    "LEGO® 2K Drive": "Welcome to Bricklandia, home of a massive open-world LEGO driving adventure.",
    "LEGO® Batman™: The Videogame": "The Caped Crusader joins forces with the super heroes of the DC Comics universe and blasts off to outer space.",
    "LEGO® Batman™ 2: DC Super Heroes": "Legends Unite! The Dynamic Duo of Batman and Robin join other famous super heroes.",
    "LEGO® Batman™ 3: Beyond Gotham": "The Caped Crusader joins forces with the super heroes of the DC Comics universe and blasts off to outer space to stop the evil Brainiac.",
    "LEGO® DC Super-Villains": "It's good to be bad… Embark on an all-new DC/LEGO adventure by becoming the best villain the universe has seen.",
    "LEGO® Jurassic World": "Following the epic storylines of Jurassic Park, The Lost World: Jurassic Park and Jurassic Park III, and the highly anticipated Jurassic World.",
    "LEGO® MARVEL Super Heroes": "Players take control of a huge roster of characters as they unite to stop Loki and a host of other Marvel villains.",
    "LEGO® MARVEL Super Heroes 2": "Join your favorite Super Heroes and Super Villains from different eras and realities as they go head-to-head with the time-traveling Kang the Conqueror.",
    "LEGO® MARVEL's Avengers": "Avengers Assemble! The best-selling LEGO Marvel videogame franchise returns with a new action-packed, Super Hero adventure.",
    "The LEGO® Movie - Videogame": "Join Emmet and an unlikely group of resistance fighters in their heroic quest to thwart Lord Business’ evil plans.",
    "The LEGO® Movie 2 - Videogame": "The alien monster invaders have left Bricksburg in ruins. It is now up to Emmet and a host of heroic characters to go beyond their world.",
    "The LEGO® NINJAGO® Movie Video Game": "Find your inner ninja with the all-new LEGO NINJAGO Movie Video Game!",
    "LEGO® STAR WARS™: The Force Awakens": "The No. 1 LEGO videogame franchise triumphantly returns with a fun-filled, humorous journey based on the blockbuster Star Wars film.",
    "LEGO® Star Wars™: The Skywalker Saga": "Play through all nine Star Wars saga films in a brand-new LEGO video game unlike any other.",
    "LEGO® The Hobbit™": "Reclaim the Lost Kingdom of Erebor. Join Bilbo Baggins, Gandalf, Thorin and his company of Dwarves.",
    "LEGO® The Incredibles": "Experience the thrilling adventures of the Parr family as they conquer crime and family life.",
    "LEGO® The Lord of the Rings™": "Based on The Lord of the Rings motion picture trilogy, LEGO® The Lord of the Rings takes players on a journey through Middle-earth.",
    "LEGO® Worlds": "Explore, discover and create together. LEGO Worlds is an open environment of procedurally-generated Worlds made entirely of LEGO bricks.",
    "Lethal Company": "Scavenge for scrap on abandoned moons to meet the Company's profit quota. Don't get eaten.",
    "Letter Quest: Grimm's Journey Remastered": "Grimm and Rose need your help to defeat a legion of monsters, ghosts, and evil bunnies using the power of words!",
    "Liar's Bar": "Take a seat at the Liar's Bar. Play dangerous card and dice games where lying is your best weapon.",
    "Lies of P": "A thrilling soulslike that takes the story of Pinocchio, turns it on its head, and sets it against the darkly elegant backdrop of the Belle Epoque era.",
    "Like a Dragon Gaiden: The Man Who Erased His Name": "Once a legendary yakuza, Kazuma Kiryu faked his own death and abandoned his name for the sake of protecting his family.",
    "Little Nightmares": "Immerse yourself in Little Nightmares, a dark whimsical tale that will confront you with your childhood fears.",
    "Little Nightmares II": "Return to a world of charming horror in Little Nightmares II, a suspense adventure game.",
    "LOCKDOWN Protocol": "A social deduction game. Work together to restore the facility, but beware the impostors among you.",
    "Lone Ruin": "A spell-based roguelike twin-stick shooter with a focus on replayability and fast-paced action.",
    "Lords of the Fallen": "A vast world awaits in the all-new, dark fantasy action-RPG. As one of the Dark Crusaders, embark on an epic quest to overthrow Adyr.",
    "Lost Judgment": "Yagami is back. Solve a new mystery that tests the limits of justice in this action-packed legal thriller.",
    "The Lost Key": "A puzzle adventure game. Find the lost key to unlock the secrets of the ancient ruins.",

    // --- M ---
    "Mad Max": "Play as Mad Max, a reluctant hero and survivor who wants nothing more than to leave the madness behind and find solace.",
    "Mafia: Definitive Edition": "Part one of the Mafia crime saga. Lost Heaven, IL, 1930s. Re-made from the ground up, rise through the ranks of the Mafia.",
    "Mafia II: Definitive Edition": "Part two of the Mafia crime saga. Empire Bay, NY, 1940s-50s. Live the life of a gangster during the Golden-era of organized crime.",
    "Mafia III: Definitive Edition": "Part three of the Mafia crime saga. 1968, New Bordeaux, LA. Build a new crime family and take revenge.",
    "Mafia: The Old Country": "Uncover the origins of organized crime in this gritty mob story set in the brutal underworld of Sicily.",
    "Magenta Horizon": "A fast-paced 2D action platformer. Slash and dash through a neon-soaked world.",
    "Mark of the Ninja: Remastered": "True Ninja gameplay. You must be silent, agile and clever to outwit your opponents in a world of gorgeous scenery and flowing animation.",
    "Martha Is Dead": "A dark first-person psychological thriller, set in 1944 Italy, that blurs the lines between reality, superstition and the tragedy of war.",
    "Martha Is Dead": "A dark first-person psychological thriller, set in 1944 Italy, that blurs the lines between reality, superstition and the tragedy of war.",
    "Marvel's Guardians of the Galaxy": "Fire up a wild ride across the cosmos with a fresh take on Marvel’s Guardians of the Galaxy.",
    "Marvel's Spider-Man 2": "Spider-Men Peter Parker and Miles Morales face the ultimate test of strength inside and outside the mask.",
    "Marvel’s Spider-Man Remastered": "Play as an experienced Peter Parker, fighting big crime and iconic villains in Marvel’s New York.",
    "Marvel's Spider-Man: Miles Morales": "Teenager Miles Morales adjusts to his new home while following in the footsteps of his mentor, Peter Parker.",
    "Mega Man Legacy Collection": "A celebration of the 8-bit history of Capcom’s iconic Blue Bomber.",
    "Mega Man Legacy Collection 2": "The legacy continues with Mega Man 7, 8, 9, and 10.",
    "Mega Man X Legacy Collection": "The action-packed Mega Man X series returns! Play as Mega Man X in the first four titles.",
    "Mega Man X Legacy Collection 2": "Complete the exciting Mega Man X saga with X5, X6, X7, and X8.",
    "Mega Man Zero/ZX Legacy Collection": "Six action-packed games from the Mega Man Zero and ZX series.",
    "Mega Man Battle Network Legacy Collection Vol. 1": "Jack in to the net! The popular Mega Man Battle Network series is back.",
    "Mega Man Battle Network Legacy Collection Vol. 2": "The second volume of the Mega Man Battle Network series collection.",
    "Mega Man 11": "Mega Man returns! The newest entry in this iconic series blends classic, challenging 2D platforming action with a fresh look.",
    "The Messenger": "As a demon army besieges his village, a young ninja ventures through a cursed world to deliver a scroll paramount to his clan’s survival.",
    "METAL GEAR SOLID - Master Collection Version": "The first 3D title in the METAL GEAR series. Tactical Espionage Action defined.",
    "METAL GEAR SOLID 2: Sons of Liberty - Master Collection": "The sequel to MGS1. Raiden infiltrates the Big Shell to stop a terrorist group.",
    "METAL GEAR SOLID 3: Snake Eater - Master Collection": "The origin story of Big Boss. Survive in the jungle and stop a nuclear threat.",
    "METAL GEAR SOLID Δ: SNAKE EATER": "A remake of the 2004 classic Metal Gear Solid 3: Snake Eater. Experience the origin story of the famed operative Big Boss.",
    "Metal Gear Solid V: Ground Zeroes": "World-famous Kojima Productions showcases the FOX Engine in this prologue to MGSV.",
    "Metal Gear Solid V: The Phantom Pain": "Ushering in a new era for the franchise with cutting-edge technology powered by the Fox Engine and open-world tactical freedom.",
    "Metaphor: ReFantazio": "A new fantasy RPG from the creators of Persona. A journey to break the curse on the kingdom.",
    "Metro 2033 Redux": "In 2013 the world was devastated by an apocalyptic event, annihilating almost all mankind and turning the earth’s surface into a poisonous wasteland.",
    "Metro: Last Light Redux": "It is the year 2034. Beneath the ruins of post-apocalyptic Moscow, in the tunnels of the Metro, the remnants of mankind are besieged by deadly threats.",
    "Metro Exodus": "Flee the shattered ruins of dead Moscow and embark on an epic, continental journey across post-apocalyptic Russia.",
    "Middle-earth™: Shadow of Mordor™": "Fight through Mordor and uncover the truth of the spirit that compels you, discover the origins of the Rings of Power, build your legend and ultimately confront the evil of Sauron.",
    "Middle-earth™: Shadow of War™": "Go behind enemy lines to forge your army, conquer Fortresses and dominate Mordor from within.",
    "Momodora: Reverie Under the Moonlight": "Explore a cursed land in this pixel art platformer. Combo and dodge your way through a variety of enemies.",
    "Momodora: Moonlit Farewell": "The latest installment in the Momodora series. Join Momo on her divine mission to save her people.",
    "MONSTER HUNTER RISE": "Rise to the challenge and join the hunt! Use the Wirebug to traverse and fight monsters in new ways.",
    "Monster Hunter Stories 2: Wings of Ruin": "A new adventure awaits you in this second installment of the turn-based RPG series set in the world of Monster Hunter.",
    "Monster Hunter: World": "Welcome to a new world! Take on the role of a hunter and slay ferocious monsters in a living, breathing ecosystem.",
    "Monster Hunter Wilds": "The unbridled force of nature runs wild. Environments transform drastically in this new Monster Hunter experience.",
    "Monster Sanctuary": "Monster taming meets Metroidvania. Collect, train and battle monsters in a lovely side-view pixel world.",
    "Mortal Kombat X": "Propels the iconic franchise into a new generation. The most brutal Kombat experience ever.",
    "Mortal Kombat 11": "The definitive MK11 experience! Take control of Earthrealm's protectors in the game's two critically acclaimed, time-bending Story Campaigns.",
    "Mortal Shell": "A deep action-RPG that tests your sanity and resilience in a shattered world. Possess lost warriors and master their combat styles.",
    "Moss": "A single-player action-adventure puzzle game in VR. Meet Quill, a young mouse with dreams of greatness.",
    "Moss: Book II": "Quill is back! In Moss: Book II, the story continues as a new tyrant threatens the world.",

    // --- N, O ---
    "Necrosmith 2": "A necromancer simulator. Assemble the dead from different body parts and upgrade your tower.",
    "NieR Replicant ver.1.22474487139...": "Discover the one-of-a-kind prequel to the critically-acclaimed masterpiece NieR:Automata.",
    "NieR:Automata™": "Invaders from another world attack without warning. To break the deadlock, a new breed of android infantry is sent into the fray.",
    "Nine Sols": "A lore-rich, hand-drawn 2D action-platformer featuring Sekiro-inspired deflection-focused combat.",
    "Nioh: Complete Edition": "Ready to die? Experience the newest brutal action game from Team NINJA and Koei Tecmo Games.",
    "Nioh 2 – The Complete Edition": "Defy your own mortality and unleash your inner darkness across the violent feudal era of Sengoku Japan.",
    "No More Heroes 3": "Travis Touchdown returns to Santa Destroy to defend Earth from an alien invasion in this hack-and-slash adventure.",
    "No Rest for the Wicked": "A visceral, precision Action RPG from the creators of the Ori series. Reinventing the genre.",
    "No, I'm not a Human": "A post-apocalyptic adventure. Play as the last human in a world dominated by robots.",
    "Oddworld: New 'n' Tasty": "Explore ancient ruins, dodge carnivorous beasts and avoid trigger-happy guards as Abe, the original Oddworld hero.",
    "Oddworld: Soulstorm Enhanced Edition": "Witness Abe's horrifying conflict with a terrifying new machination in this fresh narrative adventure.",
    "Oddworld: Stranger's Wrath HD": "In the dusty, undeveloped wastelands of Western Mudos, cantankerous townsfolk find their settlements besieged by belligerent outlaws.",
    "Okami HD": "Experience the critically acclaimed masterpiece with its renowned Sumi-e ink art style in breathtaking high resolution.",
    "OMORI": "Explore a strange world full of colorful friends and foes. Navigate through the vibrant and the mundane in order to uncover a forgotten past.",
    "Onimusha: Warlords": "Capcom’s riveting samurai adventure returns! Experience the story of Samanosuke Akechi in feudal Japan.",
    "Ori and the Blind Forest: Definitive Edition": "The forest of Nibel is dying. After a powerful storm sets a series of devastating events in motion, an unlikely hero must journey to find his courage.",
    "Ori and the Will of the Wisps": "Embark on a new journey in a vast, exotic world where you’ll encounter towering enemies and challenging puzzles on your quest to unravel Ori’s destiny.",
    "OTXO": "Enter an unexplained mansion, purge the enemies within, and unravel the secrets in this fast-paced roguelite shooter.",
    "OUTBUDDIES DX": "Run, gun, explore and blast your way through a sunken city in this underwater Metroidvania.",
    "Outlast": "Hell is an experiment you can't survive in Outlast, a first-person survival horror game developed by veterans of some of the biggest game franchises in history.",
    "Outlast 2": "Sullivan Knoth and his followers left our wicked world behind to give birth to Temple Gate, a town, deep in the wilderness and hidden from civilization.",
    "Outward Definitive Edition": "An immersive RPG sim that focuses on survival. You are not a god, nor a chosen one. You are an adventurer.",

    // --- P ---
    "Palworld": "Fight, farm, build and work alongside mysterious creatures called 'Pals' in this completely new multiplayer, open world survival and crafting game!",
    "Papers, Please": "The award-winning, dystopian document thriller. Inspect documents and stop smugglers, spies, and terrorists.",
    "Party Panic": "A crazy online and local-multiplayer party game. Compete against your friends in 30+ rapid fire minigames.",
    "Pathfinder: Wrath of the Righteous": "Embark on a journey to a realm overrun by demons in a new epic RPG from the creators of the critically acclaimed Pathfinder: Kingmaker.",
    "PAYDAY 2": "An action-packed, four-player co-op shooter that once again lets gamers don the masks of the original PAYDAY crew.",
    "PEAK.": "A mountain climbing adventure. Scale the highest peaks and survive the elements.",
    "Persona 3 Reload": "Step into the shoes of a transfer student thrust into an unexpected fate when entering the hour 'hidden' between one day and the next.",
    "Persona 5 Royal": "Don the mask and join the Phantom Thieves of Hearts as they stage grand heists, infiltrate the minds of the corrupt, and make them change their ways!",
    "Phoenix Wright: Ace Attorney Trilogy": "Become Phoenix Wright and experience the thrill of the battle as you fight to save your innocent clients in a court of law.",
    "PICO PARK": "A cooperative local/online multi-player action puzzle game for 2-8 players.",
    "Pillars of Eternity": "Prepare to be enchanted by a world where the choices you make and the paths you choose shape your destiny.",
    "Pillars of Eternity II: Deadfire": "Pursue a rogue god over land and sea in the sequel to the multi-award-winning RPG Pillars of Eternity.",
    "Pizza Tower": "A fast-paced 2D platformer inspired by the Wario Land series. Save your pizzeria from destruction.",
    "A Plague Tale: Requiem": "Heartbreaking and visually stunning, follow Amicia and Hugo on a new journey through medieval France.",
    "Pocket Bravery": "A retro-style fighting game inspired by 90s classics like Street Fighter and King of Fighters.",
    "Poly Bridge 2": "The acclaimed bridge-building simulator is back and better than ever! New levels, new mechanics, a custom physics engine.",
    "Portal": "Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon.",
    "Portal 2": "The 'Perpetual Testing Initiative' has been expanded to allow you to design co-op puzzles for you and your friends!",
    "POSTAL 4: No Regerts": "The Postal Dude is back! A satirical and outrageous open-world first-person shooter.",
    "POSTAL: Brain Damaged": "Spin-off to the Running With Scissors’ cult series. A boomer-shooter with a retro aesthetic.",
    "Praey for the Gods": "A boss-climbing open world adventure game where you play a lone hero sent to the edge of a dying frozen world.",
    "Prey": "In Prey, you awaken aboard Talos I, a space station orbiting the moon in the year 2032. You are the key subject of an experiment meant to alter humanity forever.",
    "Pseudoregalia": "A 3D platformer metroidvania. Explore a twisted dream world and unlock new movement abilities.",
    "Psychonauts": "A psychic odyssey through the minds of misfits, monsters, and madmen.",
    "Psychonauts 2": "Razputin Aquato, trained acrobat and powerful young psychic, has realized his lifelong dream of joining the international psychic espionage organization known as the Psychonauts!",
    "Pummel Party": "A 4-8 player online and local-multiplayer party game. Pummel friends or AI using a wide array of absurd items.",
    "Pyre": "A party-based RPG from the creators of Bastion and Transistor. Lead your band of exiles to freedom through a series of mystical competitions.",

    // --- Q, R ---
    "The Quarry": "When the sun goes down on the last night of summer camp, nine teenage counselors are plunged into an unpredictable night of horror.",
    "R.E.P.O.": "A co-op horror game. Repo properties from monsters and ghosts to pay off your debt.",
    "Rain World": "You are a slugcat. The world around you is full of danger, and you must face it alone.",
    "Ratchet & Clank: Rift Apart": "Blast your way through an interdimensional adventure. Ratchet and Clank make their way to PC for the first time.",
    "Re:Fresh": "A cozy game about collecting, crafting, and helping a town recover after a storm.",
    "Record of Lodoss War-Deedlit in Wonder Labyrinth-": "A 2D Metroidvania-style action game based on the hit fantasy novel Record of Lodoss War.",
    "Remnant: From the Ashes": "A third-person survival action shooter set in a post-apocalyptic world overrun by monstrous creatures.",
    "Remnant II": "The sequel to the best-selling game Remnant: From the Ashes that pits survivors of humanity against new deadly creatures and god-like bosses.",
    "Resident Evil 0": "Before the mansion, there was the train. Discover the truth behind the Mansion Incident in this prequel.",
    "Resident Evil": "The game that defined the survival horror genre is back! Check out the remastered HD version of Resident Evil.",
    "Resident Evil 2": "A deadly virus engulfs the residents of Raccoon City in September of 1998, plunging the city into chaos as flesh eating zombies roam the streets.",
    "Resident Evil 3": "Jill Valentine is one of the last remaining people in Raccoon City to witness the atrocities Umbrella performed.",
    "Resident Evil 4 (2005)": "Special agent Leon S. Kennedy is sent on a mission to rescue the U.S. President’s daughter who has been kidnapped.",
    "Resident Evil 4 (Remake)": "Survival is just the beginning. A reimagining of the 2005 classic with modernized gameplay and a reimagined storyline.",
    "Resident Evil 5": "The Umbrella Corporation and its crop of lethal viruses have been destroyed and contained. But a new, more dangerous threat has emerged.",
    "Resident Evil 6": "Blending action and survival horror, Resident Evil 6 promises to be the dramatic horror experience of 2013.",
    "Resident Evil 7 Biohazard": "Fear and isolation seep through the walls of an abandoned southern farmhouse. '7' marks a new beginning for survival horror.",
    "Resident Evil Village": "Experience survival horror like never before in the eighth major installment in the storied Resident Evil franchise.",
    "Resident Evil Revelations 2": "The beginning of the Resident Evil Revelations 2 tale sees fan favorite Claire Redfield make a dramatic return.",
    "Rise of the Tomb Raider": "Lara Croft becomes more than a survivor as she embarks on her first Tomb Raiding expedition to the most treacherous and remote regions of Siberia.",
    "Risk of Rain 2": "Escape a chaotic alien planet by fighting through hordes of frenzied monsters – with your friends, or on your own.",
    "Risk of Rain Returns": "The classic multiplayer roguelike, remastered with new survivors, items, and more.",
    "Roadwarden": "An illustrated text-based RPG that uses isometric pixel art and combines mechanics borrowed from RPGs, Visual Novels and adventure games.",
    "Rollerdrome": "A third person action shooter that seamlessly blends high octane combat with fluid motion to create a unique action experience.",
    "RV There Yet?": "A simulation game where you drive an RV across the country. Manage resources and enjoy the road trip.",
    "Ryse: Son of Rome": "Marius Titus witnesses the murder of his family at the hands of barbarians, then travels with the Roman army to Britannia to seek revenge.",

    // --- S ---
    "Saints Row IV: Re-Elected": "The Boss of the Saints has been elected President of the United States. But the Saints are just getting started.",
    "Sakuna: Of Rice and Ruin": "Discover the true power of rice in this action RPG / farming simulation.",
    "Salt and Sacrifice": "As a Marked Inquisitor, you'll journey through the western frontier: pursuing, hunting, and obliterating Mages that roam the realm.",
    "Schedule I": "A drug dealing simulator. Manufacture, distribute, and manage your empire.",
    "Sea Salt": "An action strategy hybrid where you are an Old God summoning unfathomable horrors to blight the human lands.",
    "Sekiro™: Shadows Die Twice": "Carve your own clever path to vengeance in an all-new adventure from developer FromSoftware.",
    "Shadow of the Tomb Raider": "Experience Lara Croft’s defining moment as she becomes the Tomb Raider.",
    "Shantae and the Seven Sirens": "Shantae is back in an all-new tropical adventure! Explore a vast sunken city and battle the Seven Sirens.",
    "Shenmue I & II": "A tale of revenge. Ryo Hazuki sets out to find the man responsible for his father's murder.",
    "Shift Happens": "A cooperative platformer for two. You and a friend shift your mass, throw each other and puzzle your way through the game.",
    "Shin Megami Tensei III Nocturne HD Remaster": "Reawaken your inner demon in a modernized version of the acclaimed ATLUS classic.",
    "Shin Megami Tensei V: Vengeance": "The definitive version of Shin Megami Tensei V. Forge your own path in a post-apocalyptic Tokyo.",
    "Shovel Knight: Treasure Trove": "The complete Shovel Knight saga! Play as Shovel Knight, Plague Knight, Specter Knight, and King Knight.",
    "Sid Meier's Civilization VI": "Civilization VI offers new ways to interact with your world, expand your empire across the map, advance your culture, and compete against history’s greatest leaders.",
    "Sifu": "A realistic third-person brawler with tight Kung Fu combat mechanics and cinematic martial arts action.",
    "SIGNALIS": "A classic survival horror experience set in a dystopian future where humanity has uncovered a dark secret.",
    "SILENT HILL 2": "Having received a letter from his deceased wife, James heads to where they shared so many memories, in the hope of seeing her one more time: Silent Hill.",
    "Slay the Princess — The Pristine Cut": "You're here to slay the princess. Don't believe her lies.",
    "Slay the Spire": "We fused card games and roguelikes together to make the best single player deckbuilder we could.",
    "Sleeping Dogs: Definitive Edition": "A gritty, visceral, open-world cop drama set in the vibrant city of Hong Kong.",
    "Slime-san": "Slime-san was minding his own business when he was swallowed whole by a giant worm. Now he must escape!",
    "Sniper Elite V2 Remastered": "You are elite sniper Karl Fairburne, parachuted into Berlin amidst the Germans’ final stand.",
    "Sniper Elite 3": "Stalk your targets through the twisting canyons, lush oases and ancient cities of North Africa in the deadly rush to sabotage a Nazi super-weapons programme.",
    "Sniper Elite 4": "Discover unrivalled sniping freedom in the largest and most advanced World War 2 shooter ever built.",
    "Sniper Elite 5": "The award-winning series returns as Karl Fairburne fights to uncover Project Kraken in 1944 France.",
    "Sniper Ghost Warrior Contracts 2": "Experience pure sniper gameplay across the harsh terrain of the modern day Middle East.",
    "SOULCALIBUR VI": "Introducing the newest entry in the SOULCALIBUR series! Experience all-new gameplay mechanics with the most beautiful graphics the weapons-based fighting genre has ever seen!",
    "South Park™: The Stick of Truth™": "From the perilous battlefields of the fourth-grade playground, a young hero will rise, destined to be South Park’s savior.",
    "Space Crew: Legendary Edition": "Time for your toughest mission yet! Recruit and train your crew to tackle the growing threat from alien and android armies.",
    "A Space for the Unbound": "A slice-of-life adventure game with beautiful pixel art set in late 90s rural Indonesia that tells a story about overcoming anxiety and depression.",
    "Split Fiction": "A split-screen FPS where you can look through portals to see different dimensions.",
    "Spyro™ Reignited Trilogy": "The original roast master is back! Same sick burns, same smoldering attitude, now all scaled up in stunning HD.",
    "Stardew Valley": "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.",
    "SteamWorld Dig 2": "Take your pickaxe and dig into the sequel to the award-winning SteamWorld Dig! A platform mining adventure forged in Metroidvania flames.",
    "Steelrising": "Paris, 1789. The French Revolution has been suppressed with bloodshed by Louis XVI and his merciless mechanical army. Aegis, a mysterious automaton masterpiece, must confront the king's army alone.",
    "Stick Fight: The Game": "Stick Fight is a physics-based couch/online fighting game where you battle it out as the iconic stick figures from the golden age of the internet.",
    "Strange Brigade": "Erase the rising evil in this 1930s third-person shooter! Explore the ancient ruins of Egypt, solve puzzles and blast the undead.",
    "STRANGER OF PARADISE FINAL FANTASY ORIGIN": "Jack and his allies, Ash and Jed, burn with the resolve to defeat Chaos as they throw open the gates to the Chaos Shrine.",
    "Street Fighter V": "Experience the intensity of head-to-head battle with Street Fighter V! Choose from 16 iconic characters.",
    "Street Fighter™ 6": "Powered by Capcom’s proprietary RE ENGINE, the Street Fighter 6 experience spans across three distinct game modes featuring World Tour, Fighting Ground and Battle Hub.",
    "Streets of Rage 4": "The all-time classic Streets of Rage, known for its timeless gameplay and electronic dance influenced music.",
    "Strider": "Strider returns in a brand new adventure, complete with incredible side-scrolling action, and lightning fast combat.",
    "Subnautica": "Descend into the depths of an alien underwater world filled with wonder and peril. Craft equipment, pilot submarines and out-smart wildlife to explore lush coral reefs, volcanoes, cave systems, and more.",
    "SUPERHOT VR": "Blurring the lines between cautious strategy and unbridled mayhem, SUPERHOT VR is the definitive VR FPS in which time moves only when you move.",
    "The Surge": "A catastrophic event has knocked you out during the first day on the job… you wake up equipped with a heavy-grade exoskeleton, in a destroyed section of the complex.",
    "The Surge 2": "On the way to Jericho City, your plane is shot down by a mysterious storm and crash-lands in the outskirts. You wake up weeks later in a derelict detention facility inside the city.",
    "Survivalist: Invisible Strain": "It's been ten years since the infection started. Long-established settlements are collapsing, one by one, for unknown reasons. Survivors are running to the hills to escape, hoping to set up a safe place to live.",
    "Symphony of War: The Nephilim Saga": "Enter Tahnra, a land savaged by war. You, a fresh academy graduate with humble beginnings, will grow to lead a grand army against a corrupt adversary.",

    // --- T, U, V ---
    "Talisman: Digital 5th Edition": "The classic fantasy board game returns. Quest for the Crown of Command in this digital adaptation.",
    "Talisman: Digital Classic Edition": "The officially licensed multiplayer version of the classic fantasy adventure board game.",
    "Teacup": "A wholesome narrative adventure game with a focus on exploration and non-linear progression.",
    "Team Fortress Classic": "One of the most popular online action games of all time, Team Fortress Classic features over nine character classes.",
    "TEKKEN 7": "Discover the epic conclusion of the Mishima clan and unravel the reasons behind each step of their ceaseless fight.",
    "TEKKEN 8": "Fist Meets Fate! TEKKEN 8 continues the tragic saga of the Mishima bloodline and its world-shaking father-and-son grudge matches.",
    "Thief": "Garrett, the Master Thief, steps out of the shadows into the City. In this treacherous place, where the Baron's Watch spreads a rising tide of fear and oppression, his skills are the only things he can trust.",
    "Thief Gold": "Stalk your prey on the quest for stolen goods with your blackjack, sword, and an assortment of unique arrows. Steal for money and uncover the hidden agendas of your allies and enemies.",
    "Thief™ II: The Metal Age": "The ultimate thief is back! Tread softly as you make your way through 15 new complex, non-linear levels full of loot to steal and guards to outsmart.",
    "Thief: Deadly Shadows": "You are Garrett, the master thief. Rarely seen and never caught, Garrett is the best that ever was. Able to sneak past any guard, pick any lock, and break into the most ingeniously secured residences.",
    "Thief of Thieves: Season One": "Based on the best-selling comic by Robert Kirkman, Thief of Thieves: Season One is a story of heists and the people behind them.",
    "Thymesia": "A grueling action-RPG with fast-paced combat and an intricate plague weapon system.",
    "Tiny Tina's Wonderlands": "Embark on an epic adventure full of whimsy, wonder, and high-powered weaponry! Bullets, magic, and broadswords collide across this chaotic fantasy world.",
    "Titan Souls": "Between our world and the world beyond lie the Titan Souls, the spiritual source and sum of all living things. Now scattered amongst the ruins and guarded by the idle Titans charged with their care.",
    "Tom Clancy's Rainbow Six® Siege": "Master the art of destruction and gadgetry in Tom Clancy’s Rainbow Six Siege. Face intense close quarters combat, high lethality, tactical decision making, team play and explosive action.",
    "Tomb Raider (2013)": "Tomb Raider explores the intense and gritty origin story of Lara Croft and her ascent from a young woman to a hardened survivor.",
    "Tomb Raider I": "Lara Croft is hired to recover pieces of an ancient artifact known as the Scion. She runs, jumps, swims and climbs her way towards the truth of its origin and powers.",
    "Tomb Raider II": "Lara Croft returns in Tomb Raider II. Join Lara in her quest for the Dagger of Xian, reputed to possess the power of the dragon.",
    "Tomb Raider III": "Thousands of years ago a meteor crashed into Antarctica and the shockwaves of its impact are being felt in the modern age.",
    "Tomb Raider IV: The Last Revelation": "Lara Croft discovers the lost tomb of the Egyptian God Set, unwittingly unleashing him and fulfilling an ancient prophecy.",
    "Tomb Raider V: Chronicles": "Lara Croft is missing in Egypt - presumed dead. Those closest to her gather together at the Croft Estate on a grey, rainy day for a memorial service in her honour.",
    "Tomb Raider VI: The Angel of Darkness": "A series of grisly murders brings Lara into conflict with a sinister Alchemist from the past, and a secret alliance of powerful individuals shrouded in mystery.",
    "Total War: SHOGUN 2": "In the darkest age of Japan, endless war leaves a country divided. It is the middle of the 16th Century in Feudal Japan.",
    "A Total War Saga: TROY": "In this legendary age, heroes walk the earth. In an act that shocks the world, audacious Paris, prince of Troy, elopes with the beautiful Queen of Sparta.",
    "Totally Accurate Battle Simulator": "Be the leader of red and blue wobblers from ancient lands, spooky places, and fantasy worlds.",
    "Transistor": "A sci-fi themed action RPG from the creators of Bastion. Fight your way through a stunning futuristic city.",
    "Trine Enchanted Edition": "A fantasy action game where the player can create and use physics-based objects to solve hazardous puzzles and threaten enemies.",
    "Trine 2: Complete Story": "Sidescrolling game of action, puzzles and platforming. You play as one of the Three Heroes who make their way through dangers untold in a fairytale world.",
    "Trine 3: The Artifacts of Power": "A platforming game of action, puzzles and adventure, and the sequel to the award winning Trine and Trine 2.",
    "Trine 4: The Nightmare Prince": "The Trine series returns to the magic of 2.5D! Join three iconic heroes as they set off on a quest through fantastical fairytale landscapes to save the world.",
    "Trine 5: A Clockwork Conspiracy": "The biggest Trine adventure yet! The Heroes of Trine must reunite to push back a fearsome Clockwork army and bring peace and justice to the land.",
    "Trinity Fusion": "Take control of your parallel selves on a mission to save the dying multiverse. Explore dark, sci-fi worlds and engage in fast-paced combat.",
    "TUNIC": "Explore a land filled with lost legends, ancient powers, and ferocious monsters in TUNIC, an isometric action game about a small fox on a big adventure.",
    "Ultimate Marvel vs. Capcom 3": "Marvel and Capcom join forces to deliver the most frenetic 3 vs 3 tag battles ever with Ultimate Marvel vs. Capcom 3.",
    "Ultra Street Fighter® IV": "The world’s greatest fighting game evolves to a whole new level with Ultra Street Fighter IV.",
    "Umamusume: Pretty Derby": "Train Horse Girls to be the best racers in Japan. A simulation game based on the popular anime.",
    "UNCHARTED™: Legacy of Thieves Collection": "Play as Nathan Drake and Chloe Frazer in their own standalone adventures as they confront their pasts and forge their own legacies.",
    "Undertale": "The RPG game where you don't have to destroy anyone.",
    "The Vale: Shadow of the Crown": "An audio-based action adventure game that sets out to breathe new life into medieval combat and fantasy storytelling.",
    "Vanquish": "The hit sci-fi shooter returns. An overpopulated Earth suffocating under limited resources looks to Providence, the solar-powered space colony for support.",

    // --- W, X, Y, Z ---
    "The Walking Dead: Season One": "A five-part game series set in the same universe as Robert Kirkman’s award-winning comic book series.",
    "The Walking Dead: Season Two": "The sequel to the game of the year. Clementine, a young orphan, is left to fend for herself in a world gone to hell.",
    "The Walking Dead: A New Frontier": "When family is all you have left... how far will you go to protect it?",
    "The Walking Dead: The Final Season": "Clementine, now a fierce and capable survivor, has reached the final chapter in her journey.",
    "The Walking Dead: Michonne": "A miniseries starring the blade-wielding, iconic character from Robert Kirkman's best-selling comic books.",
    "War Mongrels": "An isometric real-time tactics game that takes place on the eastern front of World War II.",
    "Warpips": "A Tug-of-War strategy game. Deploy soldiers, tanks, helicopters and planes. No micro-management, just pure strategy.",
    "Watchmen: The End Is Nigh": "A hardcore mature action game that features visceral battles in urban settings.",
    "Watchmen: The End Is Nigh Part 2": " delves further into the partnership of Rorschach and Nite Owl before the Keane Act hero ban.",
    "We Are The Dwarves": "An action-based tactical adventure with active pause (Time Dilation).",
    "We Were Here Forever": "You and your friend are trapped in the realm of Castle Rock with no way out - were you betrayed, or simply not that smart?",
    "Webbed": "Be a little spider! Swing through the trees, spin sticky webs, and make friends with bugs.",
    "WHAT THE GOLF?": "The golf game for people who hate golf. A silly physics-based golf parody where every golf course is a new surprising type of golf.",
    "The Wild Eight": "An intense survival action-adventure set in the frozen wilderness of Alaska.",
    "Windward": "Designed from the start to be a fully procedural co-op game, play by yourself or with friends and sail the high seas.",
    "The Witcher: Enhanced Edition Director's Cut": "Become The Witcher, Geralt of Rivia, a legendary monster slayer caught in a web of intrigue.",
    "The Witcher 2: Assassins of Kings Enhanced Edition": "A time of untold chaos has come. Mighty forces clash behind the scenes in a struggle for power and influence.",
    "The Witcher® 3: Wild Hunt": "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.",
    "The Wonderful 101: Remastered": "Control 100 heroes at once! Use the Unite Morph system to turn your team into giant weapons.",
    "Worms": "Throw a grenade down memory lane with the original and classic turn-based strategy game Worms™!",
    "Worms Armageddon": "Those intrepid invertebrates return with a vengeance in the much-loved Worms™ Armageddon.",
    "Worms Blast": "Fall in love with Worms™ Blast - a fast-paced action-puzzle game featuring your favorite invertebrate characters.",
    "Worms Crazy Golf": "Worms™ Crazy Golf is a hilarious mixture of the explosive action of Worms™ and the puzzle-based challenges of crazy golf!",
    "Worms Pinball": "Worms™ Pinball offers a table packed with 3D LED displays, mini-games, and all the Worms humor you expect.",
    "Worms Reloaded": "The turn-based comic mayhem continues in Worms™ Reloaded.",
    "Worms Revolution": "The latest game in the classic turn-based strategy series to come to the PC.",
    "Worms Rumble": "Worms like you’ve never played it before. Intense, real-time, arena-based 32 player cross-platform combat.",
    "Worms Ultimate Mayhem": "The definitive 3D 'Worms' game! Load your weapons and experience a whole new dimension in destructive turn-based cartoon action.",
    "Worms W.M.D": "The worms are back in their most destructive game yet. With a gorgeous, hand-drawn 2D look, brand new weapons, and crafting.",
    "Worms World Party Remastered": "Imagine taking the perfect online gaming experience and one of the most popular Worms games ever made, adding a touch of Steam achievements.",
    "WUCHANG: Fallen Feathers": "A soulslike action RPG set in the chaotic final years of the Ming Dynasty.",
    "XCOM: Enemy Unknown": "Take control of a secret paramilitary organization known as XCOM. As the XCOM commander, you will defend against a terrifying global alien invasion.",
    "XCOM® 2": "Earth has changed. Twenty years have passed since world leaders offered an unconditional surrender to alien forces.",
    "XCOM: Chimera Squad": "Five years after the events of XCOM 2, humans and aliens are working together to forge a civilization of cooperation.",
    "Yakuza 0": "The glitz, glamour, and unbridled decadence of the 80s are back in Yakuza 0.",
    "Yakuza Kiwami": "10 years ago, Kazuma Kiryu took the fall for a crime he didn’t commit to save his best friend.",
    "Yakuza Kiwami 2": "Kazuma Kiryu, the Dragon of Dojima, must travel to Sotenbori, Osaka to broker peace between the rival clans.",
    "Yakuza 3 Remastered": "Kazuma Kiryu has earned his retirement on the sandy beaches of Okinawa. But when a deadly power struggle arrives on his doorstep, he’ll have to walk the streets of Kamurocho once more.",
    "Yakuza 4 Remastered": "A murder in Tojo Clan territory sets off an investigation by a small branch of the police.",
    "Yakuza 5 Remastered": "Kazuma Kiryu travels to Fukuoka, pretending to be a taxi driver, but he is pulled back into the legendary dragon's world.",
    "Yakuza 6: The Song of Life": "Kazuma Kiryu, the Dragon of Dojima, returns for his final chapter.",
    "Zombie Army 4: Dead War": "Hitler’s hordes are back for more in this spine-chilling shooter from the makers of Sniper Elite 4."
};
