// UPDATE THIS DATE when adding a new batch of games (Format: YYYY-MM-DD)

// ==========================================
// 1. NEW UPDATES (Add new batches here)
// ==========================================
const batches = [
{
            date: "2026-03-20",
            list: [
                { name: "Alone in the Dark", id: "1310410", genre: "Action, Horror, Survival, Adventure", year: 2024, score: 64 },
                { name: "Cronos: The New Dawn", id: "2101960", genre: "Action, Horror, Survival, Sci-Fi", year: 2025, score: 79 },
                { name: "Disney Dreamlight Valley", id: "1401590", genre: "Casual, Simulation, Adventure, RPG", year: 2023, score: 74 },
                { name: "DRAGON QUEST VII Reimagined", id: "2499860", genre: "Adventure, RPG, JRPG, Turn-Based", year: 2026, score: 86, cover: "cobkan" },
                { name: "DYNASTY WARRIORS: ORIGINS", id: "2384580", genre: "Action, Hack & Slash, Musou", year: 2025, score: 76 },
                { name: "House Flipper", id: "613100", verified: true, genre: "Simulation, Casual, Indie", year: 2018, score: 68 },
                { name: "NINJA GAIDEN Σ", id: "1580780", genre: "Action, Hack & Slash, Character Action", year: 2021, score: 73 },
                { name: "NINJA GAIDEN Σ2", id: "1580790", genre: "Action, Hack & Slash, Character Action", year: 2021, score: 73 },
                { name: "NINJA GAIDEN 3: Razor's Edge", id: "1369760", verified: true, genre: "Action, Hack & Slash, Character Action", year: 2021, score: 69 },
                { name: "NINJA GAIDEN 4", id: "2627260", genre: "Action, Adventure, Hack & Slash", year: 2025, score: 85 },
                { name: "OCTOPATH TRAVELER 0", id: "3014320", verified: true, genre: "RPG, JRPG, Turn-Based, Pixel Graphics", year: 2025, score: 82 },
                { name: "Stray", id: "1332010", verified: true, genre: "Adventure, Cyberpunk, Cat, Sci-Fi", year: 2022, score: 83 }
            ]
        },
{
            date: "2026-03-16",
            list: [
                { name: "Biped", id: "1071870", verified: true, genre: "Action, Adventure, Casual, Co-op, Puzzle", year: 2020, score: 80 },
                { name: "Cook, Serve, Delicious! 3?!", id: "1000030", verified: true, genre: "Action, Indie, Simulation, Strategy, Co-op", year: 2020, score: 79 },
                { name: "DOUBLE", id: "1874190", genre: "Adventure, Indie, Psychological, Thriller, Story Rich", year: 2021 },
                { name: "HIVE", id: "832040", genre: "Action, Indie, Strategy, Sci-Fi, Multiplayer", year: 2022 },
                { name: "Our World Is Ended.", id: "940650", genre: "Adventure, Visual Novel, Story Rich, Anime, Sci-Fi", year: 2019, score: 68 },
                { name: "Sands of Aura", id: "1119840", genre: "Action, RPG, Indie, Souls-like, Adventure", year: 2023, score: 75 },
                { name: "skate.", id: "2662170", genre: "Sports, Simulation, Skateboarding, Multiplayer, Open World", year: 2025 },
                { name: "Soda Crisis", id: "1460190", verified: true, genre: "Action, Platformer, Shooter, Fast-Paced, Cyberpunk", year: 2022, score: 78 }
            ]
        },
     {
            date: "2026-03-13",
            list: [
                { name: "Monster Hunter Stories 3: Twisted Reflection", id: "2852190", genre: "RPG, JRPG, Monster Tamer, Turn-Based, Adventure", year: 2026, score: 84, release_date: "13/03/2026", cover: "coaxze" }
            ]
        },
        {
            date: "2026-03-12",
            list: [
                { name: "FATAL FRAME II: Crimson Butterfly REMAKE", id: "3920610", genre: "Horror, Survival Horror, Adventure, Atmospheric, Singleplayer", year: 2026, score: 85, release_date: "11/03/2026", cover: "coau37" },
                { name: "Amnesia: A Machine for Pigs", id: "239200", genre: "Horror, Survival Horror, Adventure, Indie, First-Person", year: 2013, score: 72, release_date: "10/09/2013" },
                { name: "Amnesia: Rebirth", id: "999220", genre: "Horror, Survival Horror, Adventure, First-Person, Story Rich", year: 2020, score: 80, release_date: "20/10/2020" },
                { name: "Amnesia: The Bunker", id: "1944430", verified: true, genre: "Horror, Survival Horror, Action, Stealth, First-Person", year: 2023, score: 78, release_date: "06/06/2023" },
                { name: "Amnesia: The Dark Descent", id: "57300", genre: "Horror, Survival Horror, Adventure, First-Person, Puzzle", year: 2010, score: 85, release_date: "08/09/2010" },
                { name: "Dark Hours: Prologue", id: "3064370", genre: "Horror, Co-op, Multiplayer, Survival Horror, First-Person", year: 2024, release_date: "18/07/2024" },
                { name: "Penumbra: Black Plague Gold Edition", id: "22120", genre: "Horror, Survival Horror, Adventure, Puzzle, First-Person", year: 2009, score: 78, release_date: "23/01/2009" },
                { name: "Penumbra: Overture", id: "22180", genre: "Horror, Survival Horror, Adventure, Puzzle, First-Person", year: 2007, score: 73, release_date: "30/03/2007" },
                { name: "Penumbra: Requiem", id: "22140", genre: "Horror, Survival Horror, Adventure, Puzzle, First-Person", year: 2008, score: 62, release_date: "31/10/2008" },
                { name: "SOMA", id: "282140", verified: true, genre: "Horror, Sci-Fi, Story Rich, Atmospheric, First-Person", year: 2015, score: 84, release_date: "22/09/2015" }
            ]
        },
    {
        date: "2026-03-11",
        list: [
            { name: "Slay the Spire 2", id: "2868840", genre: "Strategy, Card Game, Roguelike, Deckbuilder, Turn-Based", year: 2026, score: 90, release_date: "05/03/2026", verified: true, cover: "co82c5" },
            { name: "Megabonk", id: "3405340", genre: "Action, Indie, Arcade, Sandbox, Physics", year: 2025, verified: true }
        ]
    },
    {
        date: "2026-01-24",
        list: [
            { name: ".hack//G.U. Last Recode", id: "525480", verified: true, genre: "RPG, Action, JRPG, Anime, Hack & Slash", year: 2017, score: 69 },
            { name: "Manhunt", id: "12130", genre: "Action, Stealth, Horror, Thriller, Third-Person", year: 2004, score: 75 },
            { name: "Max Payne 2: The Fall of Max Payne", id: "12150", genre: "Action, Shooter, Noir, Third-Person, Narrative", year: 2003, score: 86 },
            { name: "Your Turn To Die -Death Game By Majority-", id: "2067780", verified: true, genre: "Adventure, Visual Novel, Horror, Mystery, Puzzle", year: 2023 }
        ]
    },
    {
        date: "2026-03-07",
        list: [
            { name: "Astrea: Six-Sided Oracles", id: "1755830", verified: true, genre: "Strategy, Deckbuilder, Roguelike, RPG, Indie", year: 2023, score: 85 },
            { name: "Chants of Sennaar", id: "1931770", verified: true, genre: "Adventure, Puzzle, Story Rich, Indie, Language", year: 2023, score: 86 },
            { name: "Elite Dangerous", id: "359320", genre: "Simulation, Sci-Fi, Open World, Space, MMO", year: 2015, score: 80 },
            { name: "Etrian Odyssey III HD", id: "1810820", verified: true, genre: "RPG, Dungeon Crawler, Turn-Based, JRPG, Classic", year: 2023, score: 80 },
            { name: "Hard West 2", id: "1282410", verified: true, genre: "Strategy, Turn-Based, Western, Tactical", year: 2022, score: 77 },
            { name: "Homeworld 3", id: "1840080", genre: "Strategy, RTS, Sci-Fi, Space", year: 2024, score: 75 },
            { name: "Jusant", id: "1977170", verified: true, genre: "Adventure, Puzzle, Exploration, Climbing, Indie", year: 2023, score: 83 },
            { name: "Sid Meier's Starships", id: "318240", genre: "Strategy, Turn-Based, Sci-Fi, 4X", year: 2015, score: 64 },
            { name: "SWORN", id: "1763250", verified: true, genre: "Action, Roguelike, Co-op, Hack & Slash", year: 2024 },
            { name: "Total War: EMPIRE - Definitive Edition", id: "10500", genre: "Strategy, Historical, RTS, Turn-Based, Grand Strategy", year: 2009, score: 90 },
            { name: "Total War: NAPOLEON - Definitive Edition", id: "34030", genre: "Strategy, Historical, RTS, Turn-Based, Grand Strategy", year: 2010, score: 81 },
            { name: "X-COM: Apocalypse", id: "7660", genre: "Strategy, Classic, Sci-Fi, Turn-Based, Tactical", year: 1997 },
            { name: "X-COM: Enforcer", id: "7770", genre: "Action, Shooter, Classic, Sci-Fi", year: 2001, score: 65 },
            { name: "X-COM: Interceptor", id: "7730", genre: "Simulation, Strategy, Sci-Fi, Space, Classic", year: 1998 },
            { name: "X-COM: Terror from the Deep", id: "7650", genre: "Strategy, Classic, Sci-Fi, Turn-Based, Tactical", year: 1995 },
            { name: "X-COM: UFO Defense", id: "7760", genre: "Strategy, Classic, Sci-Fi, Turn-Based, Tactical", year: 1993 }
        ]
    },
    {
        date: "2026-02-27",
        list: [
            { name: "Resident Evil Requiem", id: "3764200", verified: true, genre: "Horror, Action, Survival, Third-Person", year: 2026, score: 89, release_date: "27/02/2026", cover: "cobmj0" },
            { name: "Nioh 3", id: "3681010", verified: true, genre: "Action, RPG, Souls-like, Dark Fantasy, Co-op", year: 2026, score: 86, release_date: "06/02/2026", cover: "cobf3x" },
            { name: "CODE VEIN II", id: "2362060", verified: true, genre: "RPG, Action, Anime, Souls-like", year: 2026, score: 70, release_date: "30/01/2026", cover: "co9xhi" }
        ]
    },
    {
        date: "2026-02-20",
        list: [
            { name: "Mewgenics", id: "686060", verified: true, genre: "RPG, Rogue-like, Strategy, Simulation, Indie", year: 2026, score: 90, release_date: "10/02/2026", cover: "co9n5k" },
            { name: "Bus Simulator 21 Next Stop", id: "976590", genre: "Simulation, Vehicle, Open World, Driving, Management", year: 2021, score: 73 },
            { name: "StarVaders", id: "2463770", verified: true, genre: "Strategy, Card Game, Rogue-lite, Sci-Fi, Indie", year: 2025, score: 85 },
            { name: "SteamWorld Build", id: "2134770", verified: true, genre: "Simulation, Strategy, City Builder, Mining, Indie", year: 2023, score: 80 }
        ]
    },
    {
        date: "2026-01-12",
        list: [
            { name: "Guilty Gear X2 #Reload", id: "314030", genre: "Action, Fighting, Arcade, 2D, Anime", year: 2014, score: 86, slug: "guilty-gear-x2-reload" },
            { name: "Goat Simulator", id: "265930", verified: true, genre: "Simulation, Comedy, Sandbox, Open World, Physics", year: 2014, score: 62 }
        ]
    },
    {
        date: "2026-01-11",
        list: [
            { name: "Etrian Odyssey HD", id: "1868180", verified: true, genre: "RPG, Adventure, Dungeon Crawler, JRPG, Turn-Based", year: 2023, score: 87 },
            { name: "Punch Club", id: "394310", verified: true, genre: "Strategy, RPG, Management, Simulation, Indie", year: 2016, score: 80 },
            { name: "The Red Solstice", id: "265590", genre: "Strategy, Action, RPG, Co-op, Sci-Fi", year: 2015, score: 74 },
            { name: "SAMOLIOTIK", id: "449680", genre: "Action, Indie, Shoot 'Em Up, Arcade", year: 2016, score: 84 },
            { name: "Sniper: Ghost Warrior 2", id: "34870", verified: true, genre: "Action, Stealth, Sniper, FPS, Shooter", year: 2013, score: 74 }
        ]
    },
    {
        date: "2026-01-10",
        list: [
            { name: "ULTRAKILL", id: "1229490", verified: true, genre: "Action, FPS, Retro, Boomer Shooter, Indie, Fast-Paced", year: 2020 },
            { name: "Backpack Hero", id: "1970580", verified: true, genre: "Strategy, Roguelike, Deckbuilder, Inventory Management, Indie", year: 2023 },
            { name: "Nidhogg 2", id: "535520", verified: true, genre: "Action, Fighting, Indie, Multiplayer, Party", year: 2017, score: 72 },
            { name: "Commandos 2 - HD Remaster", id: "1100410", genre: "Strategy, Stealth, Tactics, RTS, WWII", year: 2020 },
            { name: "Commandos 3 - HD Remaster", id: "1469170", genre: "Strategy, Stealth, Tactics, RTS, WWII", year: 2022 },
            { name: "Commandos: Behind Enemy Lines", id: "6800", genre: "Strategy, Stealth, Classic, RTS, Tactical", year: 1998, score: 85 },
            { name: "Praetorians - HD Remaster", id: "1100420", genre: "Strategy, RTS, Classic, Historical, Tactics", year: 2020 },
            { name: "Sudden Strike 4", id: "373930", genre: "Strategy, RTS, WWII, Tactical, Historical", year: 2017 },
            { name: "Sudden Strike 3", id: "612540", genre: "Strategy, RTS, WWII, Tactical, Historical", year: 2007 },
            { name: "Sudden Strike 2 Gold", id: "612520", genre: "Strategy, RTS, WWII, Tactical, Historical", year: 2002 },
            { name: "Sudden Strike Gold", id: "612300", genre: "Strategy, RTS, WWII, Tactical, Historical", year: 2001 },
            { name: "Sudden Strike Resource War", id: "613600", genre: "Strategy, RTS, WWII, Tactical", year: 2005 },
            { name: "Dungeons 3", id: "493900", verified: true, genre: "Strategy, Simulation, Comedy, RTS, Dungeon Management", year: 2017, score: 74 },
            { name: "Dungeons 2", id: "262280", genre: "Strategy, Simulation, RPG, Comedy, Dungeon Management", year: 2015, score: 72 },
            { name: "Dungeons", id: "57650", genre: "Strategy, Simulation, RPG, Dungeon Management", year: 2011, score: 56 },
            { name: "Dungeons: The Dark Lord", id: "200550", genre: "Strategy, Simulation, RPG, Dungeon Management, Fantasy", year: 2011 },
            { name: "Disciples: Liberation", id: "1287840", genre: "Strategy, RPG, Dark Fantasy, Turn-Based, Tactical", year: 2021, score: 73 },
            { name: "Immortal Realms: Vampire Wars", id: "1024480", genre: "Strategy, Turn-Based, Card Game, Vampire, Dark Fantasy", year: 2020 },
            { name: "Deathbulge: Battle of the Bands", id: "1083790", genre: "RPG, Indie, Comedy, Turn-Based", year: 2023 },
            { name: "Haste", id: "1796470", genre: "Action, Racing, Indie, Arcade", year: 2025 }
        ]
    }
];

const comingSoonGames = [
    {
        name: "Crimson Desert",
        id: "3321460",
        genre: "Action, Adventure, Open World",
        year: "2026",
        release_info: "19/03/2026",
        release_type: "date",
        cover: "coaqai"
    },
    {
        name: "Death Stranding 2: On the Beach",
        id: "3280350",
        genre: "Action, Adventure, Open World, Sci-Fi, Atmospheric",
        year: "2026",
        release_info: "19/03/2026",
        release_type: "date",
        cover: "co9ipx"
    },
    {
        name: "Pragmata",
        id: "3357650",
        genre: "Action, Adventure, Sci-Fi, Atmospheric, Singleplayer",
        year: "2026",
        release_info: "16/04/2026",
        release_type: "date",
        cover: "co9wwv"
    },
    {
        name: "Mouse: P.I. For Hire",
        id: "2416450",
        genre: "Action, FPS, Retro, Noir, Shooter",
        year: "2026",
        release_info: "16/04/2026",
        release_type: "date"
    },
    {
        name: "007 First Light",
        id: "3768760",
        genre: "Action, Stealth, Shooter, Adventure, Cinematic",
        year: "2026",
        release_info: "27/05/2026",
        release_type: "date",
        cover: "coaoiz"
    },
    {
        name: "LEGO Batman",
        id: "2215200",
        genre: "Action, Adventure, LEGO, Co-op, Superhero",
        year: "2026",
        release_info: "29/05/2026",
        release_type: "date",
        cover: "coab09"
    },
    {
        name: "Metal Gear Solid Master Collection: Volume 2",
        id: "3859630",
        genre: "Action, Stealth, Classic, Tactical, Story Rich",
        year: "2026",
        release_info: "27/08/2026",
        release_type: "date",
        cover: "cobiha"
    },
    {
        name: "Phantom Blade 0",
        id: "4115450",
        genre: "Action, RPG, Hack & Slash, Souls-like, Dark Fantasy",
        year: "2026",
        release_info: "09/09/2026",
        release_type: "date",
        cover: "cob64v"
    }
];

// ==========================================
// 2. MAIN LIBRARY (The Original List)
// ==========================================

const baseLibrary = [
    { name: "999 & Virtue's Last Reward", id: "477740", genre: "Adventure, Visual Novel, Puzzle, Mystery, Thriller", year: 2017, score: 86 },
    { name: "ACE COMBAT™ 7: SKIES UNKNOWN", id: "502500", verified: true, genre: "Simulation, Action, Flight, Arcade, Combat", year: 2019, score: 78 },
    { name: "Aerial_Knights Never Yield", id: "1323540", verified: true, genre: "Action, Runner, Indie, Platformer, Rhythm", year: 2021 },
    { name: "AI War 2", id: "573410", genre: "Strategy, RTS, Sci-Fi, Indie, Tower Defense", year: 2019, score: 75 },
    { name: "AI: The Somnium Files", id: "948740", genre: "Adventure, Visual Novel, Detective, Mystery, Sci-Fi", year: 2019, score: 82 },
    { name: "AI: THE SOMNIUM FILES - nirvanA Initiative", id: "1449200", genre: "Adventure, Visual Novel, Detective, Mystery, Sci-Fi", year: 2022, score: 78 },
    { name: "Airship: Kingdoms Adrift", id: "1597310", genre: "Simulation, Strategy, Steampunk, Open World", year: 2023 },
    { name: "Alan Wake", id: "108710", verified: true, genre: "Action, Horror, Thriller, Adventure, Story Rich", year: 2012, score: 83 },
    { name: "Alan Wake's American Nightmare", id: "202750", verified: true, genre: "Action, Horror, Shooter, Thriller, Arcade", year: 2012, score: 73 },
    { name: "Alice: Madness Returns", id: "19680", genre: "Adventure, Platformer, Horror, Action, Fantasy", year: 2011, score: 75 },
    { name: "Ancestors Legacy", id: "620590", genre: "Strategy, RTS, Medieval, Historical, Tactical", year: 2018, score: 77 },
    { name: "Andro Dunos 2", id: "1856900", genre: "Action, Arcade, Shooter, Retro, Shoot 'Em Up", year: 2022 },
    { name: "Arcade Paradise", id: "1388870", verified: true, genre: "Simulation, Management, Retro, Arcade, Indie", year: 2022, score: 76 },
    { name: "ArcaniA", id: "39690", genre: "RPG, Action, Fantasy, Open World", year: 2010, score: 63 },
    { name: "ArcaniA: Fall of Setarrif", id: "65610", genre: "RPG, Action, Fantasy, Open World", year: 2011 },
    { name: "ARMORED CORE™ VI FIRES OF RUBICON™", id: "1888160", verified: true, genre: "Action, Mecha, Sci-Fi, Third-Person, Souls-like", year: 2023, score: 86 },
    { name: "Arx Fatalis", id: "1700", genre: "RPG, Immersive Sim, Fantasy, First-Person, Dungeon Crawler", year: 2002, score: 77 },
    { name: "The Ascent", id: "979690", genre: "RPG, Cyberpunk, Shooter, Action, Co-op, Isometric", year: 2021, score: 73 },
    { name: "Assassin's Creed Director's Cut", id: "15100", genre: "Action, Stealth, Open World, Adventure, Historical", year: 2008, score: 79 },
    { name: "Astalon: Tears of the Earth", id: "1046400", genre: "Action, Metroidvania, Retro, Platformer, Indie", year: 2021, score: 84 },
    { name: "Balatro", id: "2379780", verified: true, genre: "Strategy, Card Game, Roguelike, Indie, Poker", year: 2024, score: 90 },
    { name: "Baldur's Gate 3", id: "1086940", verified: true, genre: "RPG, Strategy, Turn-Based, Fantasy, Co-op, Story Rich", year: 2023, score: 96, slug: "baldurs-gate-iii" },
    { name: "Bang-On Balls: Chronicles", id: "1227650", verified: true, genre: "Action, Platformer, Sandbox, Co-op, Collectathon", year: 2023, score: 86 },
    { name: "Bastion", id: "107100", verified: true, genre: "Action, RPG, Indie, Isometric, Hack & Slash", year: 2011, score: 86 },
    { name: "Batman: Arkham Asylum GOTY Edition", id: "35140", verified: true, genre: "Action, Adventure, Superhero, Stealth, Metroidvania", year: 2010, score: 91 },
    { name: "Batman: Arkham City GOTY", id: "200260", verified: true, genre: "Action, Open World, Superhero, Adventure, Stealth", year: 2012, score: 91 },
    { name: "Batman™: Arkham Knight", id: "208650", verified: true, genre: "Action, Open World, Superhero, Adventure, Stealth", year: 2015, score: 73 },
    { name: "Batman™: Arkham Origins", id: "209000", genre: "Action, Adventure, Superhero, Open World, Stealth", year: 2013, score: 74 },
    { name: "Bayonetta", id: "460790", verified: true, genre: "Action, Hack & Slash, Spectacle, Anime, Stylish", year: 2017, score: 90 },
    { name: "Beholder: Conductor", id: "2825530", verified: true, genre: "Strategy, Simulation, Dystopian, Management, Indie", year: 2024 },
    { name: "Berserk Boy", id: "1561340", verified: true, genre: "Action, Platformer, Retro, Indie, Mega Man-like", year: 2024, score: 83 },
    { name: "Beyond: Two Souls", id: "960990", verified: true, genre: "Adventure, Interactive, Story, Cinematic, Drama", year: 2020, score: 76 },
    { name: "The Binding of Isaac: Rebirth", id: "250900", verified: true, genre: "Action, Roguelike, Indie, Bullet Hell, Top-Down", year: 2014, score: 87 },
    { name: "BioGun", id: "1219240", genre: "Action, Metroidvania, Shooter, Indie, Sci-Fi", year: 2024 },
    { name: "BIOMUTANT", id: "597820", genre: "RPG, Open World, Action, Martial Arts, Post-Apocalyptic", year: 2021, score: 66 },
    { name: "BioShock", id: "7670", verified: true, genre: "Action, FPS, Story Rich, Horror, Immersive Sim", year: 2007, score: 96 },
    { name: "BioShock 2", id: "8850", verified: true, genre: "Action, FPS, Sci-Fi, Story Rich, Horror", year: 2010, score: 88 },
    { name: "BioShock 2 Remastered", id: "409720", verified: true, genre: "Action, FPS, Remaster, Sci-Fi, Story Rich", year: 2016 },
    { name: "BioShock Infinite", id: "8870", verified: true, genre: "Action, FPS, Story Rich, Adventure, Sci-Fi", year: 2013, score: 94 },
    { name: "BioShock Remastered", id: "409710", verified: true, genre: "Action, FPS, Remaster, Story Rich, Horror", year: 2016, score: 80 },
    { name: "The Black Grimoire: Cursebreaker", id: "1183550", genre: "RPG, Open World, Medieval, Fantasy, Indie", year: 2023 },
    { name: "Black Mesa", id: "362890", verified: true, genre: "Action, FPS, Remake, Sci-Fi, Story Rich", year: 2020, score: 84 },
    { name: "Black Myth: Wukong", id: "2358720", verified: true, genre: "Action, RPG, Souls-like, Mythology, Third-Person", year: 2024, score: 81 },
    { name: "Blasphemous", id: "774361", verified: true, genre: "Action, Metroidvania, Souls-like, Platformer, Dark Fantasy", year: 2019, score: 77 },
    { name: "Bloodstained: Curse of the Moon", id: "838310", genre: "Action, Platformer, Retro, 2D, Indie", year: 2018, score: 77 },
    { name: "Bloodstained: Curse of the Moon 2", id: "1255060", genre: "Action, Platformer, Retro, 2D, Co-op", year: 2020, score: 78 },
    { name: "Bloodstained: Ritual of the Night", id: "692850", verified: true, genre: "Action, Metroidvania, RPG, Platformer, Gothic", year: 2019, score: 83 },
    { name: "Blue Prince", id: "1569580", genre: "Adventure, Puzzle, Mystery, Roguelike, Exploration", year: 2024, score: 92 },
    { name: "Bomber Crew", id: "537800", verified: true, genre: "Simulation, Strategy, Survival, WWII, Management", year: 2017, score: 75 },
    { name: "Borderlands 2", id: "49520", verified: true, genre: "Action, FPS, Looter Shooter, Co-op, Open World", year: 2012, score: 89 },
    { name: "Borderlands 3", id: "397540", verified: true, genre: "Action, FPS, Looter Shooter, Co-op, Open World", year: 2020, score: 81 },
    { name: "Bramble: The Mountain King", id: "1623940", verified: true, genre: "Adventure, Horror, Atmospheric, Puzzle, Nordic", year: 2023, score: 82 },
    { name: "Bridge Constructor Portal", id: "684410", verified: true, genre: "Simulation, Puzzle, Physics, Strategy, Comedy", year: 2017, score: 77 },
    { name: "Bright Memory: Infinite", id: "1178830", verified: true, genre: "Action, FPS, Sci-Fi, Linear, Indie", year: 2021, score: 67 },
    { name: "Broken Roads", id: "1403440", genre: "RPG, Isometric, Story Rich, Post-Apocalyptic, Turn-Based", year: 2024 },
    { name: "Brothers: A Tale of Two Sons Remake", id: "2153350", verified: true, genre: "Adventure, Puzzle, Story, Co-op, Remake", year: 2024, score: 79 },
    { name: "Buckshot Roulette", id: "2835570", genre: "Indie, Horror, Strategy, Card Game, Short", year: 2024 },
    { name: "Bully: Scholarship Edition", id: "12200", genre: "Action, Open World, School, Adventure, Comedy", year: 2008, score: 72 },
    { name: "Bulwark: Falconeer Chronicles", id: "290100", verified: true, genre: "Strategy, City Builder, Sci-Fi, Sandbox, Creative", year: 2024 },
    { name: "BUTCHER", id: "474210", genre: "Action, Platformer, Shooter, Gore, Indie", year: 2016, score: 70 },
    { name: "Call of Duty: Black Ops II", id: "202970", genre: "Action, FPS, Shooter, Zombies, Multiplayer", year: 2012, score: 74 },
    { name: "Call of Duty: Black Ops III", id: "311210", genre: "Action, FPS, Zombies, Co-op, Multiplayer", year: 2015, score: 73 },
    { name: "Call of Juarez: Bound in Blood", id: "21980", genre: "Action, FPS, Western, Co-op, Story Rich", year: 2009, score: 78 },
    { name: "Capcom Beat 'Em Up Bundle", id: "885150", verified: true, genre: "Action, Arcade, Retro, Beat 'em up, Co-op", year: 2018 },
    { name: "CARRION", id: "953490", verified: true, genre: "Action, Horror, Reverse-Horror, Metroidvania, Indie", year: 2020, score: 75 },
    { name: "Castlevania Anniversary Collection", id: "1018000", verified: true, genre: "Action, Platformer, Retro, Classic, Collection", year: 2019 },
    { name: "Castlevania Advance Collection", id: "1552550", verified: true, genre: "Action, Metroidvania, Retro, Classic, Collection", year: 2021 },
    { name: "Castle Crashers", id: "204360", verified: true, genre: "Action, Beat 'em up, Co-op, Indie, Arcade", year: 2012, score: 82 },
    { name: "Celeste", id: "504230", verified: true, genre: "Action, Platformer, Indie, Difficult, Pixel Graphics", year: 2018, score: 88 },
    { name: "Chained Together", id: "2567870", genre: "Adventure, Platformer, Co-op, Physics, Multiplayer", year: 2024 },
    { name: "Chicory: A Colorful Tale", id: "1123450", verified: true, genre: "Adventure, Indie, Puzzle, Story Rich, Creative", year: 2021, score: 90 },
    { name: "CHRONO TRIGGER", id: "613830", verified: true, genre: "RPG, JRPG, Classic, Turn-Based, Story Rich", year: 2018 },
    { name: "Citizen Sleeper", id: "1578650", verified: true, genre: "RPG, Cyberpunk, Narrative, Tabletop, Indie", year: 2022, score: 82 },
    { name: "Clair Obscur: Expedition 33", id: "1903340", verified: true, genre: "RPG, Turn-Based, Fantasy, JRPG, Story Rich", year: 2025, score: 91 },
    { name: "Clive 'N' Wrench", id: "1094720", genre: "Platformer, 3D, Adventure, Collectathon, Indie", year: 2023 },
    { name: "Cobalt Core", id: "2179850", verified: true, genre: "Strategy, Roguelike, Deckbuilder, Sci-Fi, Indie", year: 2023, score: 94 },
    { name: "CODE VEIN", id: "678960", genre: "Action, RPG, Anime, Souls-like, Co-op", year: 2019, score: 72 },
    { name: "Colt Canyon", id: "940710", verified: true, genre: "Action, Roguelike, Western, Pixel Graphics, Co-op", year: 2020 },
    { name: "Company of Heroes 3", id: "1677280", genre: "Strategy, RTS, WWII, Historical, Tactical", year: 2023, score: 81 },
    { name: "Content Warning", id: "2881650", genre: "Action, Horror, Co-op, Comedy, Multiplayer", year: 2024 },
    { name: "Control Ultimate Edition", id: "870780", verified: true, genre: "Action, Adventure, Sci-Fi, Third-Person, Metroidvania", year: 2020, score: 85 },
    { name: "Cook, Serve, Delicious!", id: "247020", verified: true, genre: "Simulation, Management, Typing, Casual, Indie", year: 2013 },
    { name: "Cook, Serve, Delicious! 2!!", id: "386620", verified: true, genre: "Simulation, Management, Co-op, Typing, Indie", year: 2017, score: 62 },
    { name: "Crash Bandicoot™ N. Sane Trilogy", id: "731490", verified: true, genre: "Action, Platformer, Remake, 3D, Family", year: 2018, score: 78 },
    { name: "CRISIS CORE –FINAL FANTASY VII– REUNION", id: "1608070", verified: true, genre: "RPG, Action, JRPG, Remaster, Story Rich", year: 2022, score: 83 },
    { name: "Crypt of the NecroDancer", id: "247080", verified: true, genre: "Action, Rhythm, Roguelike, Dungeon Crawler, Indie", year: 2015, score: 87 },
    { name: "Cuphead", id: "268910", verified: true, genre: "Action, Platformer, Difficult, Run and Gun, Co-op", year: 2017, score: 88 },
    { name: "Cyberpunk 2077", id: "1091500", verified: true, genre: "RPG, Open World, Cyberpunk, Action, FPS, Story Rich", year: 2020, score: 86 },
    { name: "Danganronpa: Trigger Happy Havoc", id: "413410", verified: true, genre: "Adventure, Visual Novel, Mystery, Anime, Puzzle", year: 2016, score: 82 },
    { name: "Danganronpa 2: Goodbye Despair", id: "413420", verified: true, genre: "Adventure, Visual Novel, Mystery, Anime, Puzzle", year: 2016, score: 83 },
    { name: "Danganronpa V3: Killing Harmony", id: "567640", verified: true, genre: "Adventure, Visual Novel, Mystery, Anime, Puzzle", year: 2017, score: 80 },
    { name: "The Dark Eye: Chains of Satinav", id: "203830", verified: true, genre: "Adventure, Point & Click, Fantasy, Story Rich, Puzzle", year: 2012, score: 75 },
    { name: "Dark Messiah of Might & Magic", id: "2100", genre: "Action, RPG, First-Person, Fantasy, Hack & Slash", year: 2006, score: 72 },
    { name: "DARK SOULS™ II: Scholar of the First Sin", id: "335300", verified: true, genre: "RPG, Action, Souls-like, Open World, Dark Fantasy", year: 2015, score: 79 },
    { name: "DARK SOULS™ III", id: "374320", verified: true, genre: "RPG, Action, Souls-like, Open World, Dark Fantasy", year: 2016, score: 89 },
    { name: "DARK SOULS™: REMASTERED", id: "570940", verified: true, genre: "RPG, Action, Souls-like, Open World, Dark Fantasy", year: 2018, score: 84 },
    { name: "Darksiders", id: "50620", genre: "Action, Adventure, Hack & Slash, Fantasy, Open World", year: 2010, score: 83 },
    { name: "Darksiders Genesis", id: "710920", verified: true, genre: "Action, RPG, Co-op, Isometric, Hack & Slash", year: 2019, score: 77 },
    { name: "Darksiders II Deathinitive Edition", id: "388410", verified: true, genre: "Action, Adventure, RPG, Hack & Slash, Open World", year: 2015 },
    { name: "Darksiders III", id: "606280", genre: "Action, Adventure, Hack & Slash, RPG, Fantasy", year: 2018, score: 70 },
    { name: "Darksiders Warmastered Edition", id: "462780", verified: true, genre: "Action, Adventure, Remaster, Hack & Slash, Fantasy", year: 2016 },
    { name: "Days Gone", id: "1259420", verified: true, genre: "Action, Open World, Zombies, Survival, Adventure", year: 2021, score: 71 },
    { name: "Dead by Daylight", id: "381210", verified: true, genre: "Action, Horror, Multiplayer, Survival, Asymmetric", year: 2016 },
    { name: "Dead Cells", id: "588650", verified: true, genre: "Action, Roguelike, Metroidvania, Platformer, Indie", year: 2018, score: 89 },
    { name: "Dead Rising 2", id: "45740", genre: "Action, Zombies, Sandbox, Open World, Co-op", year: 2010, score: 78 },
    { name: "Dead Space (2023 Remake)", id: "1693980", verified: true, genre: "Action, Horror, Sci-Fi, Survival, Third-Person", year: 2023, score: 87 },
    { name: "Dead Space 2", id: "47780", genre: "Action, Horror, Sci-Fi, Survival, Third-Person", year: 2011, score: 87 },
    { name: "Deadly Premonition: The Director's Cut", id: "247660", genre: "Adventure, Horror, Mystery, Open World, Cult Classic", year: 2013, score: 59 },
    { name: "Deadly Premonition 2", id: "1271100", verified: true, genre: "Adventure, Horror, Open World, Mystery, Cult Classic", year: 2022 },
    { name: "Death's Gambit: Afterlife", id: "356650", verified: true, genre: "Action, Metroidvania, RPG, Platformer, Souls-like", year: 2018, score: 81 },
    { name: "DEATH STRANDING DIRECTOR'S CUT", id: "1850570", verified: true, genre: "Action, Adventure, Open World, Story Rich, Sci-Fi", year: 2022, score: 85 },
    { name: "Defense Grid: The Awakening", id: "18500", genre: "Strategy, Tower Defense, Sci-Fi, Puzzle, Indie", year: 2008, score: 81 },
    { name: "Deliver Us The Moon", id: "428660", verified: true, genre: "Adventure, Sci-Fi, Story, Puzzle, Space", year: 2019, score: 68 },
    { name: "Desperados - Wanted Dead or Alive", id: "260730", genre: "Strategy, Stealth, Western, Tactics, Isometric", year: 2001, score: 78 },
    { name: "Desperados 2: Cooper’s Revenge", id: "9710", genre: "Strategy, Stealth, Western, Tactics, 3D", year: 2006, score: 66 },
    { name: "Desperados III", id: "610370", verified: true, genre: "Strategy, Stealth, Western, Tactics, Isometric", year: 2020, score: 86 },
    { name: "Destroy All Humans!", id: "803330", verified: true, genre: "Action, Open World, Comedy, Sci-Fi, Third-Person", year: 2020, score: 80 },
    { name: "Detroit: Become Human", id: "1222140", verified: true, genre: "Adventure, Story, Sci-Fi, Interactive, Cinematic", year: 2020, score: 80 },
    { name: "Deus Ex: Human Revolution - Director's Cut", id: "238010", verified: true, genre: "RPG, Cyberpunk, Stealth, Action, Immersive Sim", year: 2013, score: 91 },
    { name: "Deus Ex: Mankind Divided™", id: "337000", verified: true, genre: "RPG, Cyberpunk, Stealth, Action, Immersive Sim", year: 2016, score: 83 },
    { name: "Devil May Cry HD Collection", id: "631510", verified: true, genre: "Action, Hack & Slash, Classic, Collection, Stylish", year: 2018 },
    { name: "Devil May Cry 4 Special Edition", id: "329050", verified: true, genre: "Action, Hack & Slash, Anime, Stylish, Character Action", year: 2015 },
    { name: "Devil May Cry 5", id: "601150", verified: true, genre: "Action, Hack & Slash, Stylish, Character Action, Co-op", year: 2019, score: 89 },
    { name: "Digimon Story Cyber Sleuth: Complete Edition", id: "1042550", verified: true, genre: "RPG, JRPG, Monster Tamer, Turn-Based, Anime", year: 2019 },
    { name: "Digimon Story: Time Stranger", id: "1984270", verified: true, genre: "RPG, Strategy, Monster Tamer, JRPG, Turn-Based", year: 2025, date_added: "2025-12-24" },
    { name: "Digimon World: Next Order", id: "1530160", verified: true, genre: "RPG, Simulation, Monster Tamer, JRPG, Open World", year: 2023 },
    { name: "Disco Elysium - The Final Cut", id: "632470", verified: true, genre: "RPG, Narrative, Detective, Open World, Isometric", year: 2019, score: 97 },
    { name: "Dishonored", id: "205100", verified: true, genre: "Action, Stealth, Steampunk, Immersive Sim, First-Person", year: 2012, score: 91 },
    { name: "Dishonored 2", id: "403640", verified: true, genre: "Action, Stealth, Steampunk, Immersive Sim, First-Person", year: 2016, score: 86 },
    { name: "Dishonored®: Death of the Outsider™", id: "614570", verified: true, genre: "Action, Stealth, Steampunk, Immersive Sim, First-Person", year: 2017, score: 81 },
    { name: "Dispatch", id: "2163160", genre: "Adventure, Horror, Simulation, Indie, Mystery", year: 2024 },
    { name: "Divinity: Original Sin 2 - Definitive Edition", id: "435150", verified: true, genre: "RPG, Strategy, Turn-Based, Fantasy, Co-op, Story Rich", year: 2017, score: 93 },
    { name: "DmC: Devil May Cry", id: "220440", verified: true, genre: "Action, Hack & Slash, Stylish, Character Action, Platformer", year: 2013, score: 85 },
    { name: "Don't Starve", id: "219740", verified: true, genre: "Adventure, Survival, Indie, Crafting, Roguelike", year: 2013, score: 79 },
    { name: "Don't Starve Together", id: "322330", verified: true, genre: "Adventure, Survival, Co-op, Crafting, Multiplayer", year: 2016, score: 83 },
    { name: "DOOM (1993)", id: "2280", verified: true, genre: "Action, FPS, Classic, Retro, Boomer Shooter", year: 1993 },
    { name: "DOOM II", id: "2300", verified: true, genre: "Action, FPS, Classic, Retro, Boomer Shooter", year: 1994, score: 83 },
    { name: "DOOM 3", id: "9050", genre: "Action, Horror, FPS, Sci-Fi, Survival", year: 2004, score: 87 },
    { name: "DOOM 3: BFG Edition", id: "208200", genre: "Action, Horror, FPS, Sci-Fi, Remaster", year: 2012 },
    { name: "DOOM 64", id: "1148590", verified: true, genre: "Action, FPS, Retro, Classic, Horror", year: 2020, score: 76 },
    { name: "DOOM Eternal", id: "782330", verified: true, genre: "Action, FPS, Fast-Paced, Gore, Sci-Fi", year: 2020, score: 88 },
    { name: "Double Kick Heroes", id: "589670", genre: "Indie, Rhythm, Action, Music, Shoot 'Em Up", year: 2020, score: 73 },
    { name: "DRAGON BALL XENOVERSE 2", id: "454650", verified: true, genre: "Action, Fighting, Anime, RPG, Co-op", year: 2016, score: 78 },
    { name: "DRAGON BALL Z: KAKAROT", id: "851850", verified: true, genre: "Action, RPG, Anime, Open World, Fighting", year: 2020, score: 73 },
    { name: "DRAGON BALL: Sparking! ZERO", id: "1790600", verified: true, genre: "Action, Fighting, Anime, Arena, 3D", year: 2024, score: 83 },
    { name: "Dragon Is Dead", id: "2779530", genre: "Action, Roguelike, Platformer, Co-op, Indie", year: 2024 },
    { name: "Dragon's Dogma: Dark Arisen", id: "367500", verified: true, genre: "RPG, Action, Open World, Fantasy, Co-op", year: 2016, score: 81 },
    { name: "Dungeon Tycoon", id: "2400770", genre: "Strategy, Simulation, Management, Dungeon, Indie", year: 2024 },
    { name: "Dying Light", id: "239140", verified: true, genre: "Action, Zombies, Parkour, Open World, Co-op, Survival", year: 2015, score: 87 },
    { name: "Dying Light 2 Stay Human", id: "534380", verified: true, genre: "Action, Open World, Zombies, Parkour, RPG, Co-op", year: 2022 },
    { name: "Elden Ring", id: "1245620", verified: true, genre: "RPG, Open World, Souls-like, Dark Fantasy, Action", year: 2022, score: 94 },
    { name: "The Elder Scrolls III: Morrowind GOTY", id: "22320", genre: "RPG, Open World, Classic, Fantasy, First-Person", year: 2002, score: 89 },
    { name: "The Elder Scrolls IV: Oblivion GOTY", id: "22330", genre: "RPG, Open World, Fantasy, Classic, First-Person", year: 2007, score: 94 },
    { name: "The Elder Scrolls V: Skyrim Special Edition", id: "489830", verified: true, genre: "RPG, Open World, Fantasy, Adventure, First-Person", year: 2016, score: 74 },
    { name: "The Elder Scrolls V: Skyrim VR", id: "611670", genre: "RPG, VR, Open World, Fantasy, First-Person", year: 2018, score: 81 },
    { name: "ENDER LILIES: Quietus of the Knights", id: "1369630", verified: true, genre: "Action, Metroidvania, RPG, Dark Fantasy, Platformer", year: 2021, score: 86 },
    { name: "ENDER MAGNOLIA: Bloom in the Mist", id: "2725260", verified: true, genre: "Action, Metroidvania, RPG, Dark Fantasy, Platformer", year: 2024 },
    { name: "Enter the Gungeon", id: "311690", verified: true, genre: "Action, Roguelike, Bullet Hell, Top-Down, Co-op", year: 2016, score: 84 },
    { name: "Epic Chef", id: "1312960", genre: "Adventure, Simulation, Cooking, Farming, Indie", year: 2021 },
    { name: "Euro Truck Simulator 2", id: "227300", verified: true, genre: "Simulation, Driving, Relaxing, Open World, Management", year: 2012, score: 79 },
    { name: "Everhood", id: "1229380", verified: true, genre: "RPG, Rhythm, Indie, Bullet Hell, Story Rich", year: 2021, score: 83 },
    { name: "The Evil Within", id: "268050", verified: true, genre: "Action, Horror, Survival, Third-Person, Stealth", year: 2014, score: 68 },
    { name: "The Evil Within 2", id: "601430", verified: true, genre: "Action, Horror, Survival, Third-Person, Open World", year: 2017, score: 80 },
    { name: "Evil Genius 2: World Domination", id: "700600", verified: true, genre: "Strategy, Simulation, Villain, Management, Comedy", year: 2021, score: 70 },
    { name: "F.E.A.R.", id: "21090", genre: "Action, FPS, Horror, Tactical, Sci-Fi", year: 2005, score: 88 },
    { name: "F.E.A.R. 2: Project Origin", id: "16450", genre: "Action, FPS, Horror, Tactical, Sci-Fi", year: 2009, score: 79 },
    { name: "F.E.A.R. 3", id: "21100", genre: "Action, FPS, Co-op, Horror, Tactical", year: 2011, score: 74 },
    { name: "Fahrenheit: Indigo Prophecy Remastered", id: "312840", verified: true, genre: "Adventure, Interactive, Story, Mystery, Thriller", year: 2015 },
    { name: "Fallout 3 - Game of the Year Edition", id: "22370", genre: "RPG, Open World, Post-Apocalyptic, FPS, Story Rich", year: 2009, score: 91 },
    { name: "Fallout 4", id: "377160", verified: true, genre: "RPG, Open World, Shooter, Post-Apocalyptic, Crafting", year: 2015, score: 84 },
    { name: "Fallout: New Vegas", id: "22380", genre: "RPG, Open World, Classic, Post-Apocalyptic, Story Rich", year: 2010, score: 84 },
    { name: "Far Cry", id: "13520", genre: "Action, FPS, Open World, Stealth, Tropical", year: 2004, score: 89 },
    { name: "Far Cry 2", id: "19900", genre: "Action, FPS, Open World, Stealth, Survival", year: 2008, score: 85 },
    { name: "FINAL FANTASY", id: "1173770", verified: true, genre: "RPG, JRPG, Pixel Graphics, Classic, Turn-Based", year: 2021 },
    { name: "FINAL FANTASY II", id: "1173780", verified: true, genre: "RPG, JRPG, Pixel Graphics, Classic, Turn-Based", year: 2021 },
    { name: "FINAL FANTASY III", id: "1173790", verified: true, genre: "RPG, JRPG, Pixel Graphics, Classic, Turn-Based", year: 2021 },
    { name: "FINAL FANTASY IV", id: "1173800", verified: true, genre: "RPG, JRPG, Pixel Graphics, Classic, Turn-Based", year: 2021 },
    { name: "FINAL FANTASY V", id: "1173810", verified: true, genre: "RPG, JRPG, Pixel Graphics, Classic, Turn-Based", year: 2021 },
    { name: "FINAL FANTASY VI", id: "1173820", verified: true, genre: "RPG, JRPG, Pixel Graphics, Classic, Turn-Based", year: 2022 },
    { name: "FINAL FANTASY VII (Original)", id: "39140", verified: true, genre: "RPG, JRPG, Classic, Turn-Based, Story Rich", year: 2013 },
    { name: "FINAL FANTASY VII REMAKE INTERGRADE", id: "1462040", verified: true, genre: "RPG, Action, JRPG, Story Rich, Remake", year: 2022, score: 89 },
    { name: "FINAL FANTASY VII REBIRTH", id: "2909400", verified: true, genre: "RPG, Action, Open World, JRPG, Story Rich", year: 2025, score: 92 },
    { name: "FINAL FANTASY VIII - REMASTERED", id: "1026680", verified: true, genre: "RPG, JRPG, Remaster, Classic, Story Rich", year: 2019 },
    { name: "FINAL FANTASY IX", id: "377840", verified: true, genre: "RPG, JRPG, Classic, Turn-Based, Fantasy", year: 2016, score: 84 },
    { name: "FINAL FANTASY X/X-2 HD Remaster", id: "359870", verified: true, genre: "RPG, JRPG, Story Rich, Turn-Based, Remaster", year: 2016 },
    { name: "FINAL FANTASY XII THE ZODIAC AGE", id: "595520", verified: true, genre: "RPG, JRPG, Open World, Action, Fantasy", year: 2018 },
    { name: "FINAL FANTASY XIII", id: "292120", genre: "RPG, JRPG, Sci-Fi, Linear, Story Rich", year: 2014 },
    { name: "FINAL FANTASY XIII-2", id: "292140", genre: "RPG, JRPG, Time Travel, Story Rich", year: 2014 },
    { name: "FINAL FANTASY XV WINDOWS EDITION", id: "637650", verified: true, genre: "RPG, Open World, Action, JRPG, Story Rich", year: 2018 },
    { name: "FINAL FANTASY XVI", id: "2515020", verified: true, genre: "RPG, Action, Story Rich, JRPG, Fantasy", year: 2024, score: 88 },
    { name: "FINAL FANTASY TYPE-0 HD", id: "340170", genre: "RPG, Action, JRPG, Strategy, Military", year: 2015, score: 69 },
    { name: "Firewatch", id: "383870", verified: true, genre: "Adventure, Walking Sim, Mystery, Story Rich, Indie", year: 2016, score: 81 },
    { name: "The First Berserker: Khazan", id: "2607830", genre: "Action, RPG, Hack & Slash, Souls-like, Dark Fantasy", year: 2025 },
    { name: "Fractured Minds", id: "686340", genre: "Adventure, Horror, Short, Indie, Puzzle", year: 2017 },
    { name: "The friends of Ringo Ishikawa", id: "746940", genre: "RPG, Open World, Beat 'em up, Indie, Pixel Graphics", year: 2018 },
    { name: "Furi", id: "423230", verified: true, genre: "Action, Bullet Hell, Boss Rush, Indie, Difficult", year: 2016, score: 76 },
    { name: "Gang Beasts", id: "285900", verified: true, genre: "Party, Physics, Fighting, Multiplayer, Comedy", year: 2017 },
    { name: "Garden in!", id: "1953860", verified: true, genre: "Simulation, Relaxing, Sandbox, Casual, Indie", year: 2023 },
    { name: "Gatekeeper", id: "2106670", verified: true, genre: "Action, Roguelike, Co-op, Hack & Slash, Indie", year: 2024 },
    { name: "Gato Roboto", id: "916730", verified: true, genre: "Action, Metroidvania, Retro, Indie, Platformer", year: 2019, score: 79 },
    { name: "GeoGuessr", id: "2216710", genre: "Casual, Puzzle, Geography, Educational, Multiplayer", year: 2023 },
    { name: "Ghost of Tsushima DIRECTOR'S CUT", id: "2215430", verified: true, genre: "Action, Open World, Samurai, Adventure, Stealth", year: 2024, score: 85 },
    { name: "Ghost Trick: Phantom Detective", id: "1967430", verified: true, genre: "Adventure, Puzzle, Mystery, Story Rich, Classic", year: 2023, score: 90 },
    { name: "Ghostrunner", id: "1139900", verified: true, genre: "Action, Cyberpunk, Parkour, FPS, Fast-Paced", year: 2020, score: 81 },
    { name: "Ghostrunner 2", id: "2144740", verified: true, genre: "Action, Cyberpunk, Parkour, FPS, Fast-Paced", year: 2023, score: 81 },
    { name: "God of War", id: "1593500", verified: true, genre: "Action, Adventure, Mythology, Hack & Slash, Story Rich", year: 2022, score: 93 },
    { name: "God of War Ragnarök", id: "2322010", verified: true, genre: "Action, Adventure, Hack & Slash, Mythology, Story Rich", year: 2024, score: 90 },
    { name: "Golf With Your Friends", id: "431240", verified: true, genre: "Sports, Multiplayer, Casual, Mini Golf, Party", year: 2020 },
    { name: "Gori: Cuddly Carnage", id: "1299690", verified: true, genre: "Action, Hack & Slash, Skateboarding, Indie, Sci-Fi", year: 2024, score: 78 },
    { name: "Gothic 1 Classic", id: "65540", genre: "RPG, Open World, Classic, Fantasy, First-Person", year: 2001, score: 81 },
    { name: "Gothic II: Gold Classic", id: "39510", genre: "RPG, Open World, Classic, Fantasy, First-Person", year: 2005, score: 79 },
    { name: "Gothic 3", id: "39500", genre: "RPG, Open World, Fantasy, Classic, First-Person", year: 2006, score: 63 },
    { name: "The Great Ace Attorney Chronicles", id: "1158850", verified: true, genre: "Adventure, Visual Novel, Detective, Mystery, Historical", year: 2021, score: 83 },
    { name: "GRIME", id: "1123050", verified: true, genre: "Action, Metroidvania, Souls-like, Platformer, Dark Fantasy", year: 2021, score: 81 },
    { name: "Grotto", id: "1538850", genre: "Adventure, Narrative, Indie, Puzzle, Atmospheric", year: 2021, score: 75 },
    { name: "Guacamelee! Gold Edition", id: "214770", verified: true, genre: "Action, Metroidvania, Platformer, Co-op, Comedy", year: 2013, score: 88 },
    { name: "Guacamelee! Super Turbo Championship Edition", id: "275390", verified: true, genre: "Action, Metroidvania, Platformer, Co-op, Comedy", year: 2014 },
    { name: "Guacamelee! 2", id: "534550", verified: true, genre: "Action, Metroidvania, Platformer, Co-op, Comedy", year: 2018, score: 84 },
    { name: "GUILTY GEAR -STRIVE-", id: "1384160", verified: true, genre: "Action, Fighting, Anime, Competitive, 2D", year: 2021, score: 85 },
    { name: "Hades", id: "1145360", verified: true, genre: "Action, Roguelike, Indie, Hack & Slash, Mythology", year: 2020, score: 93 },
    { name: "Hades II", id: "1145350", verified: true, genre: "Action, Roguelike, Indie, Hack & Slash, Mythology", year: 2024, score: 94 },
    { name: "Half-Life", id: "70", verified: true, genre: "Action, FPS, Classic, Sci-Fi, Story Rich", year: 1998, score: 96 },
    { name: "Half-Life: Source", id: "280", genre: "Action, FPS, Classic, Sci-Fi, Remake", year: 2004 },
    { name: "Half-Life: Opposing Force", id: "50", genre: "Action, FPS, Classic, Sci-Fi, Military", year: 1999, score: 81 },
    { name: "Half-Life: Blue Shift", id: "130", genre: "Action, FPS, Classic, Sci-Fi", year: 2001, score: 71 },
    { name: "Half-Life 2", id: "220", verified: true, genre: "Action, FPS, Story Rich, Sci-Fi, Physics", year: 2004, score: 96 },
    { name: "Half-Life 2: Deathmatch", id: "320", genre: "Action, FPS, Multiplayer, Sci-Fi, Arena", year: 2004 },
    { name: "Half-Life: Alyx", id: "546560", genre: "Action, VR, FPS, Sci-Fi, Puzzle, Horror", year: 2020, score: 93 },
    { name: "Halo: The Master Chief Collection", id: "976730", verified: true, genre: "Action, FPS, Sci-Fi, Co-op, Collection, Multiplayer", year: 2019 },
    { name: "Hardspace: Shipbreaker", id: "1161580", verified: true, genre: "Simulation, Sci-Fi, Physics, Puzzle, Space", year: 2020, score: 83 },
    { name: "A Hat in Time", id: "253230", verified: true, genre: "Platformer, 3D, Collectathon, Adventure, Indie", year: 2017, score: 79 },
    { name: "Heavy Rain", id: "960910", verified: true, genre: "Adventure, Interactive, Story, Cinematic, Drama", year: 2020, score: 75 },
    { name: "HELLDIVERS™ 2", id: "553850", verified: true, genre: "Action, Shooter, Co-op, Sci-Fi, Third-Person", year: 2024 },
    { name: "Hi-Fi RUSH", id: "1817230", verified: true, genre: "Action, Rhythm, Hack & Slash, Platformer, Comedy", year: 2023, score: 90 },
    { name: "High On Life", id: "1583230", verified: true, genre: "Action, FPS, Comedy, Sci-Fi, Metroidvania", year: 2022, score: 67 },
    { name: "Hitman: Codename 47", id: "6900", genre: "Action, Stealth, Shooter, Classic, Third-Person", year: 2000, score: 73 },
    { name: "Hitman 2: Silent Assassin", id: "6850", genre: "Action, Stealth, Shooter, Classic, Third-Person", year: 2002, score: 87 },
    { name: "Hitman: Contracts", id: "247430", genre: "Action, Stealth, Shooter, Classic, Third-Person", year: 2004, score: 74 },
    { name: "Hitman: Blood Money", id: "6860", genre: "Action, Stealth, Classic, Sandbox, Third-Person", year: 2006, score: 82 },
    { name: "Hitman: Absolution", id: "203140", genre: "Action, Stealth, Story, Third-Person, Shooter", year: 2012, score: 79 },
    { name: "HITMAN World of Assassination", id: "1659040", verified: true, genre: "Action, Stealth, Sandbox, Puzzle, Third-Person", year: 2022, score: 87 },
    { name: "Hogwarts Legacy", id: "990080", verified: true, genre: "RPG, Open World, Magic, Adventure, Fantasy", year: 2023, score: 83 },
    { name: "Hollow Knight", id: "367520", verified: true, genre: "Action, Metroidvania, Indie, Souls-like, Platformer", year: 2017, score: 87 },
    { name: "Hollow Knight: Silksong", id: "1030300", verified: true, genre: "Action, Metroidvania, Indie, Platformer, Adventure", year: 2025, score: 90 },
    { name: "Horizon Zero Dawn™ Complete Edition", id: "1151640", verified: true, genre: "Action, Open World, RPG, Adventure, Sci-Fi", year: 2020, score: 89 },
    { name: "Horizon Forbidden West™ Complete Edition", id: "2420110", verified: true, genre: "Action, Open World, RPG, Adventure, Sci-Fi", year: 2024, score: 84 },
    { name: "Hotline Miami", id: "219150", verified: true, genre: "Action, Top-Down, Retro, Indie, Violent", year: 2012, score: 85 },
    { name: "Hotline Miami 2: Wrong Number", id: "274170", verified: true, genre: "Action, Top-Down, Retro, Indie, Violent", year: 2015, score: 74 },
    { name: "How 2 Escape", id: "2264460", genre: "Simulation, Puzzle, Co-op, Indie, Escape Room", year: 2023 },
    { name: "Human Fall Flat", id: "477160", verified: true, genre: "Puzzle, Physics, Co-op, Platformer, Multiplayer", year: 2016, score: 70 },
    { name: "Hyper Light Drifter", id: "257850", verified: true, genre: "Action, RPG, Pixel Graphics, Indie, Atmospheric", year: 2016, score: 84 },
    { name: "ibb & obb", id: "95400", verified: true, genre: "Puzzle, Co-op, Platformer, Indie, 2D", year: 2014, score: 83 },
    { name: "I Was a Teenage Exocolonist", id: "1148760", verified: true, genre: "RPG, Narrative, Card Game, Visual Novel, Sci-Fi", year: 2022, score: 91 },
    { name: "IMMORTALITY", id: "1350200", verified: true, genre: "Adventure, FMV, Mystery, Interactive, Story Rich", year: 2022, score: 87 },
    { name: "In Sound Mind", id: "1119980", genre: "Horror, Psychological, Action, FPS, Puzzle", year: 2021, score: 75 },
    { name: "Injustice: Gods Among Us Ultimate Edition", id: "242700", genre: "Action, Fighting, Superhero, Arcade, 2D", year: 2013, score: 79 },
    { name: "Injustice™ 2", id: "627270", genre: "Action, Fighting, Superhero, Competitive, 2D", year: 2017, score: 86 },
    { name: "The Inner World", id: "251430", verified: true, genre: "Adventure, Point & Click, 2D, Puzzle, Indie", year: 2013, score: 72 },
    { name: "Inscryption", id: "1092790", verified: true, genre: "Card Game, Horror, Roguelike, Puzzle, Indie", year: 2021, score: 85 },
    { name: "Instruments of Destruction", id: "1428100", genre: "Simulation, Physics, Destruction, Sandbox, Vehicles", year: 2022 },
    { name: "Intravenous 2", id: "2608270", genre: "Action, Stealth, Tactical, Top-Down, Indie", year: 2024 },
    { name: "Islets", id: "1669420", verified: true, genre: "Adventure, Metroidvania, Cute, Platformer, Indie", year: 2022 },
    { name: "JANITOR BLEEDS", id: "1552310", genre: "Horror, Retro, Puzzle, Indie, Atmospheric", year: 2022 },
    { name: "Journey", id: "638230", verified: true, genre: "Adventure, Atmospheric, Indie, Walking Sim, Artistic", year: 2020, score: 82 },
    { name: "Judgment", id: "2058180", verified: true, genre: "Action, Adventure, Crime, RPG, Story Rich", year: 2022, score: 82 },
    { name: "Just Cause", id: "6880", genre: "Action, Open World, Destruction, Shooter, Sandbox", year: 2006, score: 75 },
    { name: "Just Cause 2", id: "8190", genre: "Action, Open World, Destruction, Shooter, Sandbox", year: 2010, score: 84 },
    { name: "Just Cause 3", id: "225540", genre: "Action, Open World, Destruction, Sandbox, Shooter", year: 2015, score: 74 },
    { name: "Just Cause 4", id: "517630", genre: "Action, Open World, Destruction, Sandbox, Shooter", year: 2018, score: 68 },
    { name: "Kalimba", id: "324140", verified: true, genre: "Platformer, Puzzle, Co-op, Indie, Colorful", year: 2015, score: 81 },
    { name: "Katana ZERO", id: "460950", verified: true, genre: "Action, Platformer, Neo-Noir, Indie, Story Rich", year: 2019, score: 83 },
    { name: "Keep Talking and Nobody Explodes", id: "341800", verified: true, genre: "Puzzle, Co-op, Party, VR, Communication", year: 2015, score: 71 },
    { name: "Kill The Crows", id: "2441270", verified: true, genre: "Action, Shooter, Western, Co-op, Indie", year: 2023 },
    { name: "killer7", id: "868520", verified: true, genre: "Action, Adventure, Cult Classic, Shooter, Stylish", year: 2018, score: 78 },
    { name: "Killing Floor", id: "1250", genre: "Action, FPS, Zombies, Co-op, Survival", year: 2009, score: 72 },
    { name: "Killing Floor 2", id: "232090", genre: "Action, FPS, Zombies, Co-op, Survival", year: 2016, score: 75 },
    { name: "KINGDOM HEARTS -HD 1.5+2.5 ReMIX-", id: "2552430", verified: true, genre: "RPG, Action, Disney, JRPG, Collection", year: 2024 },
    { name: "KINGDOM HEARTS HD 2.8 Final Chapter Prologue", id: "2552440", verified: true, genre: "RPG, Action, Disney, JRPG, Collection", year: 2024 },
    { name: "KINGDOM HEARTS III + Re Mind", id: "2552450", verified: true, genre: "RPG, Action, Disney, JRPG, Hack & Slash", year: 2024 },
    { name: "Kingdom Come: Deliverance", id: "379430", verified: true, genre: "RPG, Open World, Medieval, Historical, Story Rich", year: 2018, score: 76 },
    { name: "Kingdom Come: Deliverance II", id: "1771300", verified: true, genre: "RPG, Medieval, Open World, Historical, Story Rich", year: 2025, score: 88 },
    { name: "The Last of Us™ Part I", id: "1888930", verified: true, genre: "Action, Adventure, Story Rich, Stealth, Horror", year: 2023, score: 87 },
    { name: "Left 4 Dead", id: "500", verified: true, genre: "Action, FPS, Zombies, Co-op, Multiplayer, Survival", year: 2008, score: 89 },
    { name: "LEGO® 2K Drive", id: "1451810", verified: true, genre: "Racing, Open World, LEGO, Arcade, Family", year: 2023 },
    { name: "LEGO® Batman™: The Videogame", id: "21000", verified: true, genre: "Action, Adventure, LEGO, Superhero, Co-op", year: 2008, score: 80 },
    { name: "LEGO® Batman™ 2: DC Super Heroes", id: "213330", verified: true, genre: "Action, Open World, LEGO, Superhero, Co-op", year: 2012, score: 81 },
    { name: "LEGO® Batman™ 3: Beyond Gotham", id: "313690", verified: true, genre: "Action, Adventure, LEGO, Superhero, Co-op", year: 2014 },
    { name: "LEGO® DC Super-Villains", id: "829110", verified: true, genre: "Action, Open World, LEGO, Superhero, Co-op", year: 2018, score: 76 },
    { name: "LEGO® Jurassic World", id: "352400", verified: true, genre: "Action, Adventure, LEGO, Dinosaurs, Co-op", year: 2015, score: 72 },
    { name: "LEGO® MARVEL Super Heroes", id: "249130", verified: true, genre: "Action, Open World, LEGO, Superhero, Co-op", year: 2013, score: 78 },
    { name: "LEGO® MARVEL Super Heroes 2", id: "647830", verified: true, genre: "Action, Open World, LEGO, Superhero, Co-op", year: 2017 },
    { name: "LEGO® MARVEL's Avengers", id: "405310", verified: true, genre: "Action, Open World, LEGO, Superhero, Co-op", year: 2016 },
    { name: "The LEGO® Movie - Videogame", id: "267530", verified: true, genre: "Action, Adventure, LEGO, Platformer, Co-op", year: 2014 },
    { name: "The LEGO® Movie 2 - Videogame", id: "881320", verified: true, genre: "Action, Adventure, LEGO, Platformer, Co-op", year: 2019 },
    { name: "The LEGO® NINJAGO® Movie Video Game", id: "640590", verified: true, genre: "Action, Adventure, LEGO, Martial Arts, Co-op", year: 2017 },
    { name: "LEGO® STAR WARS™: The Force Awakens", id: "438640", verified: true, genre: "Action, Adventure, LEGO, Sci-Fi, Co-op", year: 2016 },
    { name: "LEGO® Star Wars™: The Skywalker Saga", id: "920210", verified: true, genre: "Action, Open World, LEGO, Sci-Fi, Co-op", year: 2022, score: 78 },
    { name: "LEGO® The Hobbit™", id: "285160", verified: true, genre: "Action, Adventure, LEGO, Fantasy, Co-op", year: 2014 },
    { name: "LEGO® The Incredibles", id: "818320", genre: "Action, Open World, LEGO, Superhero, Co-op", year: 2018 },
    { name: "LEGO® The Lord of the Rings™", id: "214510", verified: true, genre: "Action, Adventure, LEGO, Fantasy, Co-op", year: 2012, score: 80 },
    { name: "LEGO® Worlds", id: "332310", genre: "Adventure, Sandbox, LEGO, Creative, Exploration", year: 2017 },
    { name: "Lethal Company", id: "1966720", verified: true, genre: "Horror, Co-op, Scavenging, Multiplayer, Indie", year: 2023 },
    { name: "Letter Quest: Grimm's Journey Remastered", id: "373970", genre: "Puzzle, Word Game, RPG, Casual, Indie", year: 2015 },
    { name: "Liar's Bar", id: "3097560", genre: "Simulation, Card Game, Horror, Multiplayer, Bluffing", year: 2024 },
    { name: "Lies of P", id: "1627720", verified: true, genre: "Action, RPG, Souls-like, Dark Fantasy, Story Rich", year: 2023, score: 80 },
    { name: "LIGHTNING RETURNS: FINAL FANTASY XIII", id: "345350", genre: "RPG, JRPG, Action, Open World, Story Rich", year: 2015 },
    { name: "Like a Dragon Gaiden: The Man Who Erased His Name", id: "2375550", verified: true, genre: "Action, Adventure, Crime, RPG, Story Rich", year: 2023 },
    { name: "Little Nightmares", id: "424840", verified: true, genre: "Horror, Platformer, Puzzle, Atmospheric, Indie", year: 2017, score: 81 },
    { name: "Little Nightmares II", id: "860510", verified: true, genre: "Horror, Platformer, Puzzle, Atmospheric, Co-op", year: 2021, score: 83 },
    { name: "LOCKDOWN Protocol", id: "2768560", genre: "Action, Shooter, Strategy, Co-op, Sci-Fi", year: 2024 },
    { name: "Lone Ruin", id: "1452070", genre: "Action, Roguelike, Twin Stick, Indie, Spell Casting", year: 2023 },
    { name: "Lords of the Fallen", id: "1501750", verified: true, genre: "RPG, Action, Souls-like, Dark Fantasy, Open World", year: 2023, score: 75 },
    { name: "Lost Judgment", id: "2058190", verified: true, genre: "Action, Adventure, Crime, RPG, Story Rich", year: 2022, score: 82 },
    { name: "The Lost Key", id: "2846460", genre: "Adventure, Puzzle, Mystery, Indie, Exploration", year: 2024 },
    { name: "Lost Skies", id: "1931180", genre: "Adventure, Open World, Co-op, Survival, Crafting", year: 2025 },
    { name: "Mad Max", id: "234140", verified: true, genre: "Action, Open World, Post-Apocalyptic, Vehicular Combat, Adventure", year: 2015, score: 73 },
    { name: "Mafia: Definitive Edition", id: "1030840", genre: "Action, Adventure, Crime, Open World, Story Rich, Remake", year: 2020, score: 78 },
    { name: "Mafia II: Definitive Edition", id: "1030830", genre: "Action, Adventure, Crime, Open World, Story Rich", year: 2020 },
    { name: "Mafia III: Definitive Edition", id: "360430", genre: "Action, Open World, Crime, Adventure, Story Rich", year: 2016 },
    { name: "Mafia: The Old Country", id: "1941540", genre: "Action, Adventure, Crime, Open World, Story Rich", year: 2025, score: 73 },
    { name: "Magenta Horizon", id: "2109060", genre: "Action, Platformer, Fast-Paced, Indie, Retro", year: 2023 },
    { name: "Mark of the Ninja: Remastered", id: "860950", verified: true, genre: "Action, Stealth, Platformer, 2D, Indie", year: 2018 },
    { name: "Martha Is Dead", id: "1193910", genre: "Horror, Psychological, Narrative, Adventure, Mature", year: 2022 },
    { name: "Marvel's Guardians of the Galaxy", id: "1088850", verified: true, genre: "Action, Adventure, Superhero, RPG, Story Rich", year: 2021, score: 78 },
    { name: "Marvel's Spider-Man 2", id: "2651280", verified: true, genre: "Action, Open World, Superhero, Adventure, Story Rich", year: 2025, score: 90 },
    { name: "Marvel’s Spider-Man Remastered", id: "1817070", verified: true, genre: "Action, Open World, Superhero, Adventure, Story Rich", year: 2022, score: 86 },
    { name: "Marvel's Spider-Man: Miles Morales", id: "1817190", verified: true, genre: "Action, Open World, Superhero, Adventure, Story Rich", year: 2022, score: 84 },
    { name: "Mega Man Legacy Collection", id: "363440", verified: true, genre: "Action, Platformer, Retro, Classic, Collection", year: 2015, score: 85 },
    { name: "Mega Man Legacy Collection 2", id: "495050", genre: "Action, Platformer, Retro, Classic, Collection", year: 2017 },
    { name: "Mega Man X Legacy Collection", id: "743890", genre: "Action, Platformer, Retro, Classic, Collection", year: 2018 },
    { name: "Mega Man X Legacy Collection 2", id: "743900", genre: "Action, Platformer, Retro, Classic, Collection", year: 2018 },
    { name: "Mega Man Zero/ZX Legacy Collection", id: "999020", verified: true, genre: "Action, Platformer, Retro, Classic, Collection", year: 2020 },
    { name: "Mega Man Battle Network Legacy Collection Vol. 1", id: "1798010", verified: true, genre: "Action, RPG, Retro, JRPG, Collection, Tactical", year: 2023, score: 80 },
    { name: "Mega Man Battle Network Legacy Collection Vol. 2", id: "1798020", verified: true, genre: "Action, RPG, Retro, JRPG, Collection, Tactical", year: 2023, score: 80 },
    { name: "Mega Man 11", id: "742300", verified: true, genre: "Action, Platformer, Classic, 2D, Indie", year: 2018, score: 82 },
    { name: "The Messenger", id: "764790", verified: true, genre: "Action, Platformer, Retro, Metroidvania, Indie", year: 2018, score: 83 },
    { name: "METAL GEAR SOLID - Master Collection Version", id: "2131630", verified: true, genre: "Action, Stealth, Classic, Tactical, Story Rich", year: 2023 },
    { name: "METAL GEAR SOLID 2: Sons of Liberty - Master Collection", id: "2131640", verified: true, genre: "Action, Stealth, Classic, Tactical, Story Rich", year: 2023 },
    { name: "METAL GEAR SOLID 3: Snake Eater - Master Collection", id: "2131650", verified: true, genre: "Action, Stealth, Survival, Tactical, Story Rich", year: 2023 },
    { name: "METAL GEAR SOLID Δ: SNAKE EATER", id: "2417610", genre: "Action, Stealth, Remake, Tactical, Story Rich", year: 2025 },
    { name: "Metal Gear Solid V: Ground Zeroes", id: "311340", verified: true, genre: "Action, Stealth, Sandbox, Tactical, Third-Person", year: 2014, score: 80 },
    { name: "Metal Gear Solid V: The Phantom Pain", id: "287700", verified: true, genre: "Action, Stealth, Open World, Tactical, Sandbox", year: 2015, score: 91 },
    { name: "Metaphor: ReFantazio", id: "2679460", verified: true, genre: "RPG, JRPG, Fantasy, Turn-Based, Story Rich", year: 2024, score: 92 },
    { name: "Metro 2033 Redux", id: "286690", verified: true, genre: "Action, FPS, Horror, Post-Apocalyptic, Atmospheric", year: 2014 },
    { name: "Metro: Last Light Redux", id: "287390", verified: true, genre: "Action, FPS, Horror, Post-Apocalyptic, Atmospheric", year: 2014, score: 76 },
    { name: "Metro Exodus", id: "412020", verified: true, genre: "Action, FPS, Open World, Post-Apocalyptic, Horror", year: 2019, score: 85 },
    { name: "Middle-earth™: Shadow of Mordor™", id: "241930", verified: true, genre: "Action, Adventure, Open World, RPG, Fantasy", year: 2014, score: 84 },
    { name: "Middle-earth™: Shadow of War™", id: "356190", verified: true, genre: "Action, Adventure, Open World, RPG, Fantasy", year: 2017 },
    { name: "Momodora: Reverie Under the Moonlight", id: "428550", genre: "Action, Metroidvania, Pixel Graphics, Indie, Platformer", year: 2016, score: 82 },
    { name: "Momodora: Moonlit Farewell", id: "1747760", genre: "Action, Metroidvania, Pixel Graphics, Indie, Platformer", year: 2024, score: 84 },
    { name: "MONSTER HUNTER RISE", id: "1446780", verified: true, genre: "Action, RPG, Co-op, Hunting, JRPG", year: 2022, score: 86 },
    { name: "Monster Hunter Stories 2: Wings of Ruin", id: "1277400", verified: true, genre: "RPG, JRPG, Monster Tamer, Turn-Based, Adventure", year: 2021, score: 82 },
    { name: "Monster Hunter: World", id: "582010", verified: true, genre: "Action, RPG, Co-op, Hunting, Open World", year: 2018, score: 88 },
    { name: "Monster Hunter Wilds", id: "2246340", genre: "Action, RPG, Open World, Co-op, Hunting", year: 2025 },
    { name: "Monster Sanctuary", id: "814370", verified: true, genre: "RPG, Metroidvania, Monster Tamer, Platformer, Indie", year: 2020, score: 81 },
    { name: "Mortal Kombat X", id: "307780", verified: true, genre: "Action, Fighting, Gore, Competitive, 2D", year: 2015, score: 84 },
    { name: "Mortal Kombat 11", id: "976310", verified: true, genre: "Action, Fighting, Gore, Competitive, Story Rich", year: 2019, score: 82 },
    { name: "Mortal Shell", id: "1110910", verified: true, genre: "Action, RPG, Souls-like, Dark Fantasy, Indie", year: 2020, score: 70 },
    { name: "Moss", id: "846470", genre: "Adventure, VR, Puzzle, Platformer, Cute", year: 2018, score: 81 },
    { name: "Moss: Book II", id: "2059670", genre: "Adventure, VR, Puzzle, Platformer, Fantasy", year: 2022 },
    { name: "Necrosmith 2", id: "2277320", genre: "Strategy, Simulation, Tower Defense, Roguelike, Indie", year: 2024 },
    { name: "NieR Replicant ver.1.22474487139...", id: "1113560", verified: true, genre: "Action, RPG, JRPG, Story Rich, Hack & Slash", year: 2021, score: 83 },
    { name: "NieR:Automata™", id: "524220", verified: true, genre: "Action, RPG, JRPG, Open World, Story Rich, Hack & Slash", year: 2017, score: 84 },
    { name: "Nine Sols", id: "1809540", verified: true, genre: "Action, Metroidvania, Souls-like, Platformer, Indie", year: 2024, score: 87 },
    { name: "Nioh: Complete Edition", id: "485510", verified: true, genre: "Action, RPG, Souls-like, Co-op, Dark Fantasy", year: 2017, score: 84 },
    { name: "Nioh 2 – The Complete Edition", id: "1325200", verified: true, genre: "Action, RPG, Souls-like, Co-op, Dark Fantasy", year: 2021, score: 86 },
    { name: "No More Heroes 3", id: "1744330", genre: "Action, Hack & Slash, Stylish, Anime, Comedy", year: 2022, score: 64 },
    { name: "No Rest for the Wicked", id: "1371980", verified: true, genre: "RPG, Action, Isometric, Souls-like, Dark Fantasy", year: 2024 },
    { name: "No, I'm not a Human", id: "2330830", genre: "Adventure, Indie, Weird, Puzzle, Short", year: 2024 },
    { name: "Oddworld: New 'n' Tasty", id: "314660", genre: "Platformer, Puzzle, Remake, Classic, Adventure", year: 2015, score: 86 },
    { name: "Oddworld: Soulstorm Enhanced Edition", id: "619390", genre: "Platformer, Puzzle, Adventure, Cinematic, Strategy", year: 2022, score: 73 },
    { name: "Oddworld: Stranger's Wrath HD", id: "15750", genre: "Action, Adventure, Shooter, FPS, Western", year: 2010 },
    { name: "Okami HD", id: "587620", verified: true, genre: "Adventure, Action, Classic, Artistic, Open World", year: 2017, score: 92 },
    { name: "OMORI", id: "1150690", verified: true, genre: "RPG, Horror, Psychological, Indie, Turn-Based, Story Rich", year: 2020, score: 87 },
    { name: "Onimusha: Warlords", id: "761600", verified: true, genre: "Action, Adventure, Samurai, Hack & Slash, Classic", year: 2019 },
    { name: "Ori and the Blind Forest: Definitive Edition", id: "387290", verified: true, genre: "Platformer, Metroidvania, Atmospheric, Indie, Story Rich", year: 2016, score: 88 },
    { name: "Ori and the Will of the Wisps", id: "1057090", verified: true, genre: "Platformer, Metroidvania, Atmospheric, Indie, Story Rich", year: 2020, score: 88 },
    { name: "OTXO", id: "1608640", verified: true, genre: "Action, Roguelike, Shooter, Top-Down, Indie", year: 2023, score: 81 },
    { name: "OUTBUDDIES DX", id: "1083310", verified: true, genre: "Adventure, Metroidvania, Co-op, Retro, Indie", year: 2019, score: 66 },
    { name: "Outlast", id: "238320", verified: true, genre: "Horror, Survival, First-Person, Stealth, Indie", year: 2013, score: 80 },
    { name: "Outlast 2", id: "414700", genre: "Horror, Survival, First-Person, Stealth, Story Rich", year: 2017, score: 75 },
    { name: "Outward Definitive Edition", id: "794260", verified: true, genre: "RPG, Survival, Open World, Co-op, Fantasy", year: 2022 },
    { name: "Palworld", id: "1623730", verified: true, genre: "Action, Survival, Monster Tamer, Open World, Co-op, Crafting", year: 2024 },
    { name: "Papers, Please", id: "239030", verified: true, genre: "Simulation, Puzzle, Dystopian, Indie, Story Rich", year: 2013, score: 85 },
    { name: "Party Panic", id: "506500", genre: "Party, Multiplayer, Minigames, Physics, Comedy", year: 2016 },
    { name: "Pathfinder: Wrath of the Righteous", id: "1184370", genre: "RPG, CRPG, Fantasy, Turn-Based, Isometric, Story Rich", year: 2021, score: 83 },
    { name: "PAYDAY 2", id: "218620", verified: true, genre: "Action, FPS, Co-op, Heist, Stealth", year: 2013, score: 79 },
    { name: "PEAK.", id: "2561570", genre: "Adventure, Indie, Short, Walking Sim, Atmospheric", year: 2024 },
    { name: "Persona 3 Reload", id: "2161700", verified: true, genre: "RPG, JRPG, Anime, Turn-Based, Story Rich", year: 2024, score: 89 },
    { name: "Persona 5 Royal", id: "1687950", verified: true, genre: "RPG, JRPG, Anime, Turn-Based, Story Rich", year: 2022, score: 95 },
    { name: "Phoenix Wright: Ace Attorney Trilogy", id: "787480", verified: true, genre: "Adventure, Visual Novel, Detective, Puzzle, Anime", year: 2019 },
    { name: "PICO PARK", id: "1509960", verified: true, genre: "Party, Puzzle, Co-op, Multiplayer, Indie", year: 2021 },
    { name: "Pillars of Eternity", id: "291650", genre: "RPG, CRPG, Fantasy, Isometric, Story Rich", year: 2015, score: 89 },
    { name: "Pillars of Eternity II: Deadfire", id: "560130", genre: "RPG, CRPG, Pirates, Isometric, Story Rich", year: 2018, score: 88 },
    { name: "Pizza Tower", id: "2231450", verified: true, genre: "Platformer, 2D, Fast-Paced, Indie, Retro", year: 2023, score: 94 },
    { name: "A Plague Tale: Requiem", id: "1182900", verified: true, genre: "Adventure, Stealth, Story Rich, Action, Medieval", year: 2022, score: 82 },
    { name: "Pocket Bravery", id: "1555150", genre: "Action, Fighting, Retro, 2D, Indie", year: 2023, score: 74 },
    { name: "Poly Bridge 2", id: "1062160", genre: "Simulation, Puzzle, Physics, Bridge Building, Indie", year: 2020 },
    { name: "Portal", id: "400", verified: true, genre: "Puzzle, FPS, Sci-Fi, Comedy, Story Rich", year: 2007, score: 90 },
    { name: "Portal 2", id: "620", verified: true, genre: "Puzzle, FPS, Co-op, Sci-Fi, Story Rich", year: 2011, score: 95 },
    { name: "POSTAL 4: No Regerts", id: "707030", genre: "Action, Open World, Comedy, FPS, Crude", year: 2022 },
    { name: "POSTAL: Brain Damaged", id: "1359980", verified: true, genre: "Action, FPS, Boomer Shooter, Retro, Comedy", year: 2022, score: 71 },
    { name: "Praey for the Gods", id: "494430", verified: true, genre: "Adventure, Survival, Open World, Boss Rush, Indie", year: 2021 },
    { name: "Prey", id: "480490", verified: true, genre: "Action, Immersive Sim, Sci-Fi, FPS, Horror", year: 2017, score: 80 },
    { name: "Pseudoregalia", id: "2365810", verified: true, genre: "Platformer, 3D, Metroidvania, Indie, Fast-Paced", year: 2023 },
    { name: "Psychonauts", id: "3830", genre: "Platformer, 3D, Adventure, Comedy, Psychic", year: 2005, score: 87 },
    { name: "Psychonauts 2", id: "607080", verified: true, genre: "Platformer, 3D, Adventure, Comedy, Psychic", year: 2021, score: 89 },
    { name: "Pummel Party", id: "880940", genre: "Party, Multiplayer, Board Game, Minigames, Physics", year: 2018 },
    { name: "Pyre", id: "462770", genre: "RPG, Strategy, Sports, Narrative, Indie", year: 2017, score: 82 },
    { name: "The Quarry", id: "1577120", genre: "Horror, Cinematic, Choice Matters, Story Rich, Multiplayer", year: 2022 },
    { name: "R.E.P.O.", id: "3073980", genre: "Action, Shooter, Sci-Fi, Co-op, Horror", year: 2024 },
    { name: "Rain World", id: "312520", verified: true, genre: "Adventure, Survival, Platformer, Difficult, Indie", year: 2017, score: 66 },
    { name: "Ratchet & Clank: Rift Apart", id: "1895880", verified: true, genre: "Action, Platformer, Sci-Fi, Adventure, Third-Person", year: 2023, score: 86 },
    { name: "Re:Fresh", id: "2297650", verified: true, genre: "Casual, Simulation, Relaxing, Indie, Puzzle", year: 2023 },
    { name: "Record of Lodoss War-Deedlit in Wonder Labyrinth-", id: "1203630", genre: "Action, Metroidvania, Pixel Graphics, Anime, Platformer", year: 2021, score: 79 },
    { name: "Remnant: From the Ashes", id: "617290", verified: true, genre: "Action, RPG, Soulslike, Co-op, Third-Person, Shooter", year: 2019, score: 78 },
    { name: "Remnant II", id: "1282100", verified: true, genre: "Action, RPG, Soulslike, Co-op, Third-Person, Shooter", year: 2023, score: 80 },
    { name: "Resident Evil 0", id: "339340", genre: "Horror, Survival, Classic, Puzzle, Co-op", year: 2016 },
    { name: "Resident Evil", id: "304240", verified: true, genre: "Horror, Survival, Remake, Classic, Puzzle", year: 2015, score: 82 },
    { name: "Resident Evil 2", id: "883710", verified: true, genre: "Horror, Survival, Remake, Third-Person, Action", year: 2019, score: 89 },
    { name: "Resident Evil 3", id: "952060", verified: true, genre: "Horror, Survival, Remake, Action, Third-Person", year: 2020, score: 77 },
    { name: "Resident Evil 4 (2005)", id: "254700", genre: "Horror, Action, Classic, Third-Person, Survival", year: 2014, score: 79 },
    { name: "Resident Evil 4 (Remake)", id: "2050650", verified: true, genre: "Horror, Action, Survival, Third-Person, Remake", year: 2023, score: 91 },
    { name: "Resident Evil 5", id: "21690", genre: "Horror, Action, Co-op, Third-Person, Shooter", year: 2009, score: 86 },
    { name: "Resident Evil 6", id: "221040", verified: true, genre: "Horror, Action, Co-op, Third-Person, Shooter", year: 2013, score: 69 },
    { name: "Resident Evil 7 Biohazard", id: "418370", verified: true, genre: "Horror, Survival, FPS, First-Person, Atmospheric", year: 2017, score: 83 },
    { name: "Resident Evil Village", id: "1196590", verified: true, genre: "Horror, Survival, FPS, Action, Gothic", year: 2021, score: 83 },
    { name: "Resident Evil Revelations 2", id: "287290", genre: "Horror, Survival, Episodic, Co-op, Action", year: 2015 },
    { name: "Rise of the Tomb Raider", id: "391220", verified: true, genre: "Action, Adventure, Exploration, Open World, Stealth", year: 2016, score: 86 },
    { name: "Risk of Rain 2", id: "632360", verified: true, genre: "Action, Roguelike, Third-Person, Co-op, Sci-Fi", year: 2019, score: 85 },
    { name: "Risk of Rain Returns", id: "1337520", verified: true, genre: "Action, Roguelike, Platformer, Co-op, Pixel Graphics", year: 2023 },
    { name: "Roadwarden", id: "1155970", genre: "RPG, Text-Based, Narrative, Indie, Fantasy", year: 2022, score: 83 },
    { name: "Rollerdrome", id: "1294420", verified: true, genre: "Action, Shooter, Sports, Skating, Sci-Fi", year: 2022, score: 79 },
    { name: "RV There Yet?", id: "2892390", genre: "Simulation, Driving, Open World, Relaxing, Indie", year: 2024 },
    { name: "Ryse: Son of Rome", id: "302510", verified: true, genre: "Action, Hack & Slash, Historical, Combat, Cinematic", year: 2014, score: 61 },
    { name: "Saints Row IV: Re-Elected", id: "314580", verified: true, genre: "Action, Open World, Comedy, Sci-Fi, Co-op", year: 2013 },
    { name: "Sakuna: Of Rice and Ruin", id: "1356670", verified: true, genre: "RPG, Farming, Platformer, Simulation, Action, Japanese", year: 2020, score: 82 },
    { name: "Salt and Sacrifice", id: "1439390", genre: "Action, RPG, Soulslike, Co-op, Dark Fantasy", year: 2023 },
    { name: "Schedule I", id: "2973410", genre: "Simulation, Management, Indie, Open World, Crime", year: 2024 },
    { name: "Sea Salt", id: "983350", verified: true, genre: "Strategy, Action, Pixel Graphics, Lovecraftian, Indie", year: 2019 },
    { name: "Sekiro: Shadows Die Twice", id: "814380", verified: true, genre: "Action, Souls-like, Ninja, Stealth, Difficult", year: 2019, score: 88 },
    { name: "Shadow of the Tomb Raider", id: "750920", verified: true, genre: "Action, Adventure, Stealth, Puzzle, Exploration", year: 2018, score: 77 },
    { name: "Shantae and the Seven Sirens", id: "1191630", verified: true, genre: "Platformer, Metroidvania, Anime, Action, Indie", year: 2020 },
    { name: "Shenmue I & II", id: "758330", genre: "Action, Adventure, Open World, Classic, Martial Arts", year: 2018 },
    { name: "Shift Happens", id: "359840", verified: true, genre: "Platformer, Puzzle, Co-op, Physics, Indie", year: 2017 },
    { name: "Shin Megami Tensei III Nocturne HD Remaster", id: "1413480", verified: true, genre: "RPG, JRPG, Turn-Based, Dark Fantasy, Classic", year: 2021, score: 79 },
    { name: "Shin Megami Tensei V: Vengeance", id: "1875830", verified: true, genre: "RPG, JRPG, Turn-Based, Dark Fantasy, Demon", year: 2024, score: 90 },
    { name: "Shovel Knight: Treasure Trove", id: "250760", verified: true, genre: "Platformer, Retro, Action, Indie, 2D", year: 2014, score: 85 },
    { name: "Sid Meier's Civilization VI", id: "289070", verified: true, genre: "Strategy, 4X, Turn-Based, Historical, Empire Building", year: 2016, score: 88 },
    { name: "Sifu", id: "2138710", verified: true, genre: "Action, Fighting, Difficult, Martial Arts, Roguelike", year: 2023, score: 81 },
    { name: "SIGNALIS", id: "1262350", verified: true, genre: "Horror, Survival, Retro, Sci-Fi, Puzzle", year: 2022, score: 82 },
    { name: "Silent Hill f", id: "2947440", genre: "Horror, Psychological, Survival, Japanese, Adventure", year: 2025 },
    { name: "SILENT HILL 2", id: "2124490", verified: true, genre: "Horror, Psychological, Remake, Survival, Story Rich", year: 2024, score: 84 },
    { name: "Slay the Princess — The Pristine Cut", id: "1989270", verified: true, genre: "Adventure, Visual Novel, Horror, Romance, Indie", year: 2023, score: 90 },
    { name: "Slay the Spire", id: "646570", verified: true, genre: "Strategy, Card Game, Roguelike, Deckbuilder, Indie", year: 2019, score: 89 },
    { name: "Sleeping Dogs: Definitive Edition", id: "307690", verified: true, genre: "Action, Open World, Martial Arts, Crime, Adventure", year: 2014, score: 77 },
    { name: "Slime-san", id: "473530", genre: "Platformer, Indie, Fast-Paced, Difficult, 2D", year: 2017, score: 78 },
    { name: "Sniper Elite V2 Remastered", id: "728740", genre: "Action, Shooter, Stealth, Tactical, WWII", year: 2019, score: 61 },
    { name: "Sniper Elite 3", id: "238090", genre: "Action, Shooter, Stealth, Tactical, WWII", year: 2014, score: 71 },
    { name: "Sniper Elite 4", id: "312660", verified: true, genre: "Action, Shooter, Stealth, Tactical, WWII", year: 2017, score: 78 },
    { name: "Sniper Elite 5", id: "1029690", genre: "Action, Shooter, Stealth, Tactical, WWII", year: 2022, score: 79 },
    { name: "Sniper Ghost Warrior Contracts 2", id: "1338770", verified: true, genre: "Action, Shooter, Stealth, Tactical, Sniper", year: 2021 },
    { name: "SOULCALIBUR VI", id: "544750", genre: "Action, Fighting, Arcade, 3D, Competitive", year: 2018, score: 80 },
    { name: "South Park™: The Stick of Truth™", id: "213670", verified: true, genre: "RPG, Comedy, Turn-Based, Adventure, Story Rich", year: 2014, score: 85 },
    { name: "Space Crew: Legendary Edition", id: "1176710", verified: true, genre: "Simulation, Strategy, Sci-Fi, Management, Co-op", year: 2020 },
    { name: "A Space for the Unbound", id: "1201270", verified: true, genre: "Adventure, Pixel Graphics, Story, Indie, Atmospheric", year: 2023, score: 85 },
    { name: "Split Fiction", id: "1236860", verified: true, genre: "Action, Adventure, Co-op, Story Rich, Platformer", year: 2024, score: 86 },
    { name: "Spyro™ Reignited Trilogy", id: "996580", verified: true, genre: "Platformer, 3D, Remake, Collectathon, Family", year: 2019 },
    { name: "Stardew Valley", id: "413150", verified: true, genre: "RPG, Farming, Simulation, Indie, Relaxing, Pixel Graphics", year: 2016, score: 89 },
    { name: "SteamWorld Dig 2", id: "571310", verified: true, genre: "Platformer, Metroidvania, Mining, Indie, Adventure", year: 2017, score: 85 },
    { name: "Steelrising", id: "1283400", genre: "Action, RPG, Soulslike, Steampunk, Third-Person", year: 2022, score: 68 },
    { name: "Stick Fight: The Game", id: "674940", verified: true, genre: "Action, Fighting, Party, Physics, Multiplayer", year: 2017 },
    { name: "Strange Brigade", id: "312670", genre: "Action, Shooter, Co-op, Adventure, 1930s", year: 2018, score: 68 },
    { name: "STRANGER OF PARADISE FINAL FANTASY ORIGIN", id: "1358700", genre: "Action, RPG, Soulslike, JRPG, Hack & Slash", year: 2023 },
    { name: "Street Fighter V", id: "310950", genre: "Action, Fighting, Competitive, 2D, Arcade", year: 2016, score: 89 },
    { name: "Street Fighter™ 6", id: "1364780", verified: true, genre: "Action, Fighting, Competitive, 2D, Arcade", year: 2023, score: 92 },
    { name: "Streets of Rage 4", id: "985890", verified: true, genre: "Action, Beat 'em up, Co-op, Retro, Pixel Graphics", year: 2020, score: 84 },
    { name: "Strider", id: "235210", verified: true, genre: "Action, Platformer, Hack & Slash, Arcade, Retro", year: 2014, score: 78 },
    { name: "Subnautica", id: "264710", verified: true, genre: "Survival, Exploration, Sci-Fi, Open World, Crafting", year: 2018, score: 87 },
    { name: "SUPERHOT VR", id: "617830", genre: "Action, VR, FPS, Indie, Time Manipulation", year: 2017, score: 83 },
    { name: "The Surge", id: "378540", genre: "Action, RPG, Soulslike, Sci-Fi, Third-Person", year: 2017, score: 72 },
    { name: "The Surge 2", id: "644830", verified: true, genre: "Action, RPG, Soulslike, Sci-Fi, Third-Person", year: 2019, score: 76 },
    { name: "Survivalist: Invisible Strain", id: "1054510", verified: true, genre: "Survival, Strategy, Zombies, Management, Indie", year: 2020 },
    { name: "Symphony of War: The Nephilim Saga", id: "1488200", verified: true, genre: "RPG, Strategy, Turn-Based, Tactical, Pixel Graphics", year: 2022, score: 81 },
    { name: "Talisman: Digital 5th Edition", id: "2827230", genre: "Strategy, Board Game, Fantasy, Digital, Turn-Based", year: 2024 },
    { name: "Talisman: Digital Classic Edition", id: "247000", genre: "Strategy, Board Game, Fantasy, Digital, Turn-Based", year: 2014 },
    { name: "Teacup", id: "1445170", genre: "Adventure, Casual, Narrative, Cute, Indie", year: 2021 },
    { name: "Team Fortress Classic", id: "20", genre: "Action, FPS, Multiplayer, Classic, Team-Based", year: 1999 },
    { name: "TEKKEN 7", id: "389730", verified: true, genre: "Action, Fighting, Competitive, 3D, Arcade", year: 2017, score: 82 },
    { name: "Tekken 8", id: "1778820", verified: true, genre: "Fighting, Arcade, Action, 3D, Competitive", year: 2024, score: 91 },
    { name: "Thief", id: "239160", genre: "Action, Stealth, Adventure, First-Person, Reboot", year: 2014, score: 70 },
    { name: "Thief Gold", id: "211600", genre: "Action, Stealth, Classic, First-Person, Immersive Sim", year: 1999, score: 92 },
    { name: "Thief™ II: The Metal Age", id: "211740", genre: "Action, Stealth, Classic, First-Person, Immersive Sim", year: 2000, score: 87 },
    { name: "Thief: Deadly Shadows", id: "6980", genre: "Action, Stealth, Adventure, First-Person, Fantasy", year: 2004, score: 85 },
    { name: "Thief of Thieves: Season One", id: "726200", genre: "Adventure, Stealth, Story, Episodic, Comic Book", year: 2018 },
    { name: "Thymesia", id: "1343240", verified: true, genre: "Action, Soulslike, Fast-Paced, RPG, Gothic", year: 2022, score: 69 },
    { name: "Tiny Tina's Wonderlands", id: "1286680", verified: true, genre: "Action, FPS, Looter Shooter, RPG, Fantasy, Co-op", year: 2022 },
    { name: "Titan Souls", id: "297130", genre: "Action, Indie, Boss Rush, Pixel Graphics, Difficult", year: 2015, score: 74 },
    { name: "Tom Clancy's Rainbow Six® Siege", id: "359550", genre: "Action, FPS, Tactical, Multiplayer, Competitive", year: 2015 },
    { name: "Tomb Raider (2013)", id: "203160", verified: true, genre: "Action, Adventure, Story, Open World, Stealth", year: 2013, score: 86 },
    { name: "Tomb Raider I", id: "224960", genre: "Action, Adventure, Classic, Platformer, Puzzle", year: 1996 },
    { name: "Tomb Raider II", id: "225300", genre: "Action, Adventure, Classic, Platformer, Puzzle", year: 1997 },
    { name: "Tomb Raider III", id: "225320", genre: "Action, Adventure, Classic, Platformer, Puzzle", year: 1998 },
    { name: "Tomb Raider IV: The Last Revelation", id: "224980", genre: "Action, Adventure, Classic, Platformer, Puzzle", year: 1999 },
    { name: "Tomb Raider V: Chronicles", id: "225000", genre: "Action, Adventure, Classic, Platformer, Puzzle", year: 2000 },
    { name: "Tomb Raider VI: The Angel of Darkness", id: "225020", genre: "Action, Adventure, Classic, Third-Person, Dark", year: 2003 },
    { name: "Total War: SHOGUN 2", id: "34330", verified: true, genre: "Strategy, RTS, Historical, Turn-Based, Military", year: 2011, score: 90 },
    { name: "A Total War Saga: TROY", id: "1099410", genre: "Strategy, RTS, Historical, Turn-Based, Mythology", year: 2021 },
    { name: "Totally Accurate Battle Simulator", id: "508440", verified: true, genre: "Simulation, Strategy, Physics, Comedy, Sandbox", year: 2021 },
    { name: "Transistor", id: "237930", verified: true, genre: "Action, RPG, Sci-Fi, Isometric, Indie, Story Rich", year: 2014, score: 83 },
    { name: "Trine Enchanted Edition", id: "35700", genre: "Platformer, Puzzle, Fantasy, Co-op, Physics", year: 2009, score: 80 },
    { name: "Trine 2: Complete Story", id: "35720", genre: "Platformer, Puzzle, Fantasy, Co-op, Physics", year: 2013, score: 84 },
    { name: "Trine 3: The Artifacts of Power", id: "319910", genre: "Platformer, Puzzle, Fantasy, Co-op, 3D", year: 2015, score: 61 },
    { name: "Trine 4: The Nightmare Prince", id: "690640", verified: true, genre: "Platformer, Puzzle, Fantasy, Co-op, Physics", year: 2019, score: 81 },
    { name: "Trine 5: A Clockwork Conspiracy", id: "1436700", verified: true, genre: "Platformer, Puzzle, Fantasy, Co-op, Physics", year: 2023, score: 78 },
    { name: "Trinity Fusion", id: "1911360", verified: true, genre: "Action, Roguelike, Platformer, Sci-Fi, Hack & Slash", year: 2023, score: 80 },
    { name: "TUNIC", id: "553420", verified: true, genre: "Adventure, Puzzle, Isometric, Indie, Zelda-like", year: 2022, score: 85 },
    { name: "Ultimate Marvel vs. Capcom 3", id: "357190", verified: true, genre: "Action, Fighting, Superhero, Arcade, 2D, Crossover", year: 2017 },
    { name: "Ultra Street Fighter® IV", id: "45760", genre: "Action, Fighting, Competitive, 2D, Arcade", year: 2014, score: 82 },
    { name: "Umamusume: Pretty Derby", id: "2976450", genre: "Simulation, Racing, Anime, Management, Gacha", year: 2024 },
    { name: "UNCHARTED™: Legacy of Thieves Collection", id: "1659420", verified: true, genre: "Action, Adventure, Story, Third-Person, Cinematic", year: 2022 },
    { name: "Undertale", id: "391540", verified: true, genre: "RPG, Indie, Story Rich, Turn-Based, Bullet Hell", year: 2015, score: 92 },
    { name: "The Vale: Shadow of the Crown", id: "989790", verified: true, genre: "Adventure, Audio, RPG, Accessibility, Indie", year: 2021 },
    { name: "Vanquish", id: "460810", verified: true, genre: "Action, Shooter, Sci-Fi, Third-Person, Fast-Paced", year: 2017, score: 78 },
    { name: "The Walking Dead: Season One", id: "207610", verified: true, genre: "Adventure, Story, Zombies, Point & Click, Episodic", year: 2012, score: 82 },
    { name: "The Walking Dead: Season Two", id: "261030", verified: true, genre: "Adventure, Story, Zombies, Point & Click, Episodic", year: 2013, score: 80 },
    { name: "The Walking Dead: A New Frontier", id: "536220", verified: true, genre: "Adventure, Story, Zombies, Point & Click, Episodic", year: 2016, score: 81 },
    { name: "The Walking Dead: The Final Season", id: "866800", verified: true, genre: "Adventure, Story, Zombies, Point & Click, Episodic", year: 2019, score: 77 },
    { name: "The Walking Dead: Michonne", id: "429570", genre: "Adventure, Story, Zombies, Point & Click, Episodic", year: 2016 },
    { name: "War Mongrels", id: "1101790", genre: "Strategy, Tactics, WWII, Stealth, Isometric", year: 2021 },
    { name: "Warpips", id: "1291010", genre: "Strategy, RTS, Roguelike, Indie, Military", year: 2022 },
    { name: "Watchmen: The End Is Nigh", id: "21010", genre: "Action, Beat 'em up, Superhero, Co-op, Brawler", year: 2009, score: 61 },
    { name: "Watchmen: The End Is Nigh Part 2", id: "21030", genre: "Action, Beat 'em up, Superhero, Co-op, Brawler", year: 2009, score: 44 },
    { name: "We Are The Dwarves", id: "395570", genre: "Action, Strategy, Indie, Tactical, RPG", year: 2016, score: 60 },
    { name: "We Were Here Forever", id: "1341290", verified: true, genre: "Puzzle, Co-op, Adventure, Mystery, First-Person", year: 2022, score: 79 },
    { name: "Webbed", id: "1390350", verified: true, genre: "Platformer, Physics, Cute, Indie, 2D", year: 2021, score: 84 },
    { name: "WHAT THE GOLF?", id: "785790", verified: true, genre: "Casual, Physics, Comedy, Sports, Indie", year: 2020, score: 83 },
    { name: "The Wild Eight", id: "526160", genre: "Survival, Adventure, Co-op, Crafting, Isometric", year: 2019 },
    { name: "Windward", id: "326410", genre: "Adventure, RPG, Naval, Procedural, Co-op", year: 2015, score: 61 },
    { name: "The Witcher: Enhanced Edition Director's Cut", id: "20900", genre: "RPG, Fantasy, Story Rich, Open World, Dark Fantasy", year: 2008, score: 86 },
    { name: "The Witcher 2: Assassins of Kings Enhanced Edition", id: "20920", genre: "RPG, Fantasy, Story Rich, Action, Dark Fantasy", year: 2011, score: 88 },
    { name: "The Witcher® 3: Wild Hunt", id: "292030", verified: true, genre: "RPG, Open World, Story Rich, Fantasy, Dark Fantasy", year: 2015, score: 93 },
    { name: "The Wonderful 101: Remastered", id: "1190400", verified: true, genre: "Action, Strategy, Platinum, Hack & Slash, Superhero", year: 2020, score: 85 },
    { name: "Worms", id: "70640", genre: "Strategy, Turn-Based, Classic, Artillery, Multiplayer", year: 1995 },
    { name: "Worms Armageddon", id: "217200", verified: true, genre: "Strategy, Turn-Based, Classic, Artillery, Multiplayer", year: 1999 },
    { name: "Worms Blast", id: "70650", genre: "Strategy, Puzzle, Action, Casual, Arcade", year: 2002, score: 73 },
    { name: "Worms Crazy Golf", id: "70620", genre: "Strategy, Sports, Puzzle, Casual, Arcade", year: 2011 },
    { name: "Worms Pinball", id: "70660", genre: "Strategy, Pinball, Casual, Arcade, Indie", year: 2011 },
    { name: "Worms Reloaded", id: "22600", genre: "Strategy, Turn-Based, Classic, Artillery, Multiplayer", year: 2010, score: 79 },
    { name: "Worms Revolution", id: "200170", genre: "Strategy, Turn-Based, Physics, Artillery, Multiplayer", year: 2012, score: 73 },
    { name: "Worms Rumble", id: "1186040", genre: "Action, Shooter, Battle Royale, Multiplayer, Worms", year: 2020, score: 58 },
    { name: "Worms Ultimate Mayhem", id: "70600", genre: "Strategy, 3D, Turn-Based, Artillery, Multiplayer", year: 2011, score: 66 },
    { name: "Worms W.M.D", id: "327030", verified: true, genre: "Strategy, Turn-Based, Classic, Artillery, Co-op", year: 2016, score: 79 },
    { name: "Worms World Party Remastered", id: "270910", genre: "Strategy, Turn-Based, Classic, Artillery, Multiplayer", year: 2015 },
    { name: "WUCHANG: Fallen Feathers", id: "2505460", genre: "Action, RPG, Soulslike, Dark Fantasy, Chinese", year: 2025 },
    { name: "XCOM: Enemy Unknown", id: "200510", genre: "Strategy, Turn-Based, Sci-Fi, Tactical, Squad-Based", year: 2012, score: 89 },
    { name: "XCOM® 2", id: "268500", verified: true, genre: "Strategy, Turn-Based, Sci-Fi, Tactical, Squad-Based", year: 2016, score: 88 },
    { name: "XCOM: Chimera Squad", id: "882100", genre: "Strategy, Turn-Based, Sci-Fi, Tactical, Squad-Based", year: 2020, score: 74 },
    { name: "Yakuza 0", id: "638970", verified: true, genre: "Action, Adventure, Crime, RPG, Open World, Beat 'em up", year: 2018, score: 86 },
    { name: "Yakuza Kiwami", id: "834530", verified: true, genre: "Action, Adventure, Crime, RPG, Open World", year: 2019, score: 80 },
    { name: "Yakuza Kiwami 2", id: "927380", verified: true, genre: "Action, Adventure, Crime, RPG, Open World", year: 2019, score: 82 },
    { name: "Yakuza 3 Remastered", id: "1088710", verified: true, genre: "Action, Adventure, Crime, RPG, Open World", year: 2021, score: 72 },
    { name: "Yakuza 4 Remastered", id: "1105500", verified: true, genre: "Action, Adventure, Crime, RPG, Open World", year: 2021, score: 76 },
    { name: "Yakuza 5 Remastered", id: "1105510", verified: true, genre: "Action, Adventure, Crime, RPG, Open World", year: 2021, score: 75 },
    { name: "Yakuza 6: The Song of Life", id: "1388590", verified: true, genre: "Action, Adventure, Crime, RPG, Open World, Story Rich", year: 2021, score: 83 },
    { name: "Zombie Army 4: Dead War", id: "694280", verified: true, genre: "Action, Shooter, Zombies, Co-op, Third-Person", year: 2021, score: 74 },
]; // End of baseLibrary

// ==========================================
// 3. SYSTEM MERGE (Auto-Date Logic)
// ==========================================
// This combines the batches with the base library and stamps the dates.
// [IMPORTANT: Ensure the 'baseLibrary' array from your original file is kept here]
// For this update, I am assuming the user will keep their large list below.
// If you are replacing the whole file, PASTE THE FULL BASELIBRARY HERE.

const games = [
    // 1. Process New Batches (Newest First)
    ...batches.flatMap(batch =>
        batch.list.map(game => ({ ...game, date_added: batch.date }))
    ),
    // 2. Add Base Library
    ...baseLibrary
    // Ensure baseLibrary is defined or pasted here
];
